### ISSUE TITLE
Library 'libnode.so' not found on API < 21

### ISSUE THREAD

**Issue by GuiRitter** [janeasystems/nodejs-mobile#103]
Hi everyone.

I followed the [Getting Started](https://code.janeasystems.com/nodejs-mobile/getting-started-android) and all worked well. However, I wanted to use this on lower APIs. In `build.gradle`, I lowered `minSdkVersion` to 15. It worked on a real device and a virtual one, both with API 23. However, it didn't work neither on a real device nor a virtual one, both with API 19.

On the real device, I get this error:
```
08-08 15:46:20.201 3240-3240/? D/dalvikvm: Late-enabling CheckJNI
08-08 15:46:20.281 3240-3240/com.yourorg.sample D/ActivityThread: handleBindApplication:com.yourorg.sample
08-08 15:46:20.301 3240-3240/com.yourorg.sample D/dalvikvm: Trying to load lib /data/app-lib/com.yourorg.sample-1/libnative-lib.so 0x41cf8f98
08-08 15:46:20.321 3240-3240/com.yourorg.sample E/dalvikvm: dlopen("/data/app-lib/com.yourorg.sample-1/libnative-lib.so") failed: dlopen failed: could not load library "libnode.so" needed by "libnative-lib.so"; caused by cannot locate symbol "sigfillset" referenced by "libnode.so"...
08-08 15:46:20.321 3240-3240/com.yourorg.sample W/dalvikvm: Exception Ljava/lang/UnsatisfiedLinkError; thrown while initializing Lcom/yourorg/sample/MainActivity;
    Class init failed in newInstance call (Lcom/yourorg/sample/MainActivity;)
08-08 15:46:20.321 3240-3240/com.yourorg.sample D/AndroidRuntime: Shutting down VM
08-08 15:46:20.321 3240-3240/com.yourorg.sample W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x4168dbc0)
08-08 15:46:20.321 3240-3240/com.yourorg.sample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.yourorg.sample, PID: 3240
    java.lang.UnsatisfiedLinkError: dlopen failed: could not load library "libnode.so" needed by "libnative-lib.so"; caused by cannot locate symbol "sigfillset" referenced by "libnode.so"...
        at java.lang.Runtime.loadLibrary(Runtime.java:364)
        at java.lang.System.loadLibrary(System.java:526)
        at com.yourorg.sample.MainActivity.<clinit>(MainActivity.java:21)
        at java.lang.Class.newInstanceImpl(Native Method)
        at java.lang.Class.newInstance(Class.java:1208)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1068)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2288)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2493)
        at android.app.ActivityThread.access$800(ActivityThread.java:166)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5584)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
        at dalvik.system.NativeStart.main(Native Method)
```

I was getting a different error on the virtual device, but when I went to reproduce it again to copy the error, it generated the same error as above.

Is it possible to use this toolkit on older APIs?

Thanks in advance.

**Comment by jaimecbernardo** [comment]
Hi @GuiRitter ,

The error is occurring because nodejs-mobile is trying to locate the "sigfillset" symbol, which I think was only available since API 21 (Lollipop).

The nodejs-mobile is built for API 21, as specified here: https://github.com/janeasystems/nodejs-mobile/blob/9e90dd8c14fce5b047aa16d00e22a8ef44222a99/android-configure#L58

You could try rebuilding it for another API level by changing that line, but it might not be successful. The API level for nodejs was already at 21 before this fork. Please let us know if you are successful.

**Comment by GuiRitter** [comment]
Thanks for you reply. It's not critical for me to support APIs lower than 21, at least for now, so I won't be able to test it right now. But thanks for confirming that currently the minimum level is indeed 21.

You can close this issue if you want, unless you want to keep it open for someone else to test building it for a lower API.

**Comment by Informatic** [comment]
By cherrypicking a bunch of commits for libuv I've been so far able to run nodejs-mobile on API 19 emulator. This breaks arm64/x86_64 builds, as these are only supported since API 21, however I think it should work fine to just mix and match libnode.so built on different API versions. Also a minor patch in nodejs-mobile-react-native to use custom `setenv` wrapper instead of `Os.setenv` (available since API 21)

I'll do further testing this week and might be able to help in getting it merged, if anyone is interested in that.

https://github.com/Informatic/nodejs-mobile/commits/mobile-master-api19
https://github.com/Informatic/nodejs-mobile-react-native/commits/unstable

**Comment by Informatic** [comment]
Considering new libuv version with commits that I've cherrypicked earlier to support API 19 has landed in current master branch, the only commit that is left to (from previous testing) is https://github.com/Informatic/nodejs-mobile/commit/77e664ddbb8bb0ac15ec07c8e9ba54e5c1956876

Will verify this sometime next week and make a PR if that is in fact the only patch needed to support API 19.
