### ISSUE TITLE
cordova plugin causing an build issue

### ISSUE THREAD

**Issue by salihonder** [janeasystems/nodejs-mobile#114]
ENVIRONMENT
Node version: v6.11.3

Cordova version: 7.1.0

Config.xml file: 

<?xml version='1.0' encoding='utf-8'?>
<widget id="io.salih.hellocordova" version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>HelloCordova</name>
    <description>
        A sample Apache Cordova application that responds to the deviceready event.
    </description>
    <author email="dev@cordova.apache.org" href="http://cordova.io">
        Apache Cordova Team
    </author>
    <content src="index.html" />
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <platform name="android">
        <allow-intent href="market:*" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
    </platform>
    <engine name="ios" spec="^4.4.0" />
    <plugin name="cordova-plugin-whitelist" spec="^1.3.3" />
    <plugin name="nodejs-mobile-cordova" spec="^0.2.1" />
    <plugin name="cordova-plugin-console" spec="^1.1.0" />
</widget>

Plugins: 

cordova-plugin-console,cordova-plugin-whitelist,nodejs-mobile-cordova

iOS platform:

Xcode 9.4.1
Build version 9F2000

=============================
cordova build ios 

=========ERROR===============
ld: warning: ignoring file HelloCordova/Plugins/nodejs-mobile-cordova/NodeMobile.framework/NodeMobile, missing required architecture armv7 in file HelloCordova/Plugins/nodejs-mobile-cordova/NodeMobile.framework/NodeMobile (2 slices)
Undefined symbols for architecture armv7:
  "_node_start", referenced from:
      +[NodeJSRunner startNodeJSEngine] in NodeJSRunner.o
  "_napi_open_handle_scope", referenced from:
      Channel::invokeNodeListener(char*) in cordova-bridge.o
  "_napi_get_reference_value", referenced from:
      Channel::invokeNodeListener(char*) in cordova-bridge.o
  "_napi_define_properties", referenced from:
      Init(napi_env__*, napi_value__*) in cordova-bridge.o
  "_napi_close_handle_scope", referenced from:
      Channel::invokeNodeListener(char*) in cordova-bridge.o
  "_uv_default_loop", referenced from:
      Channel::setNapiRefs(napi_env__*&, napi_ref__*&) in cordova-bridge.o
  "_napi_call_function", referenced from:
      Channel::invokeNodeListener(char*) in cordova-bridge.o
  "_napi_create_string_utf8", referenced from:
      Method_GetDataDir(napi_env__*, napi_callback_info__*) in cordova-bridge.o
      Channel::invokeNodeListener(char*) in cordova-bridge.o
  "_napi_coerce_to_string", referenced from:
      Method_SendMessage(napi_env__*, napi_callback_info__*) in cordova-bridge.o
  "_napi_get_value_string_utf8", referenced from:
      Method_RegisterChannel(napi_env__*, napi_callback_info__*) in cordova-bridge.o
      Method_SendMessage(napi_env__*, napi_callback_info__*) in cordova-bridge.o
  "_napi_typeof", referenced from:
      Method_RegisterChannel(napi_env__*, napi_callback_info__*) in cordova-bridge.o
      Method_SendMessage(napi_env__*, napi_callback_info__*) in cordova-bridge.o
  "_napi_module_register", referenced from:
      _register_cordova_bridge() in cordova-bridge.o
  "_napi_create_reference", referenced from:
      Method_RegisterChannel(napi_env__*, napi_callback_info__*) in cordova-bridge.o
  "_napi_get_cb_info", referenced from:
      Method_RegisterChannel(napi_env__*, napi_callback_info__*) in cordova-bridge.o
      Method_SendMessage(napi_env__*, napi_callback_info__*) in cordova-bridge.o
  "_napi_get_global", referenced from:
      Channel::invokeNodeListener(char*) in cordova-bridge.o
  "_napi_get_last_error_info", referenced from:
      Method_RegisterChannel(napi_env__*, napi_callback_info__*) in cordova-bridge.o
      Method_SendMessage(napi_env__*, napi_callback_info__*) in cordova-bridge.o
      Method_GetDataDir(napi_env__*, napi_callback_info__*) in cordova-bridge.o
      Init(napi_env__*, napi_value__*) in cordova-bridge.o
  "_napi_is_exception_pending", referenced from:
      Method_RegisterChannel(napi_env__*, napi_callback_info__*) in cordova-bridge.o
      Method_SendMessage(napi_env__*, napi_callback_info__*) in cordova-bridge.o
      Method_GetDataDir(napi_env__*, napi_callback_info__*) in cordova-bridge.o
      Init(napi_env__*, napi_value__*) in cordova-bridge.o
  "_napi_throw_error", referenced from:
      Method_RegisterChannel(napi_env__*, napi_callback_info__*) in cordova-bridge.o
      Channel::setNapiRefs(napi_env__*&, napi_ref__*&) in cordova-bridge.o
      Method_SendMessage(napi_env__*, napi_callback_info__*) in cordova-bridge.o
      Method_GetDataDir(napi_env__*, napi_callback_info__*) in cordova-bridge.o
      Init(napi_env__*, napi_value__*) in cordova-bridge.o
  "_uv_async_init", referenced from:
      Channel::setNapiRefs(napi_env__*&, napi_ref__*&) in cordova-bridge.o
  "_uv_async_send", referenced from:
      Channel::flushQueue() in cordova-bridge.o
      Channel::setNapiRefs(napi_env__*&, napi_ref__*&) in cordova-bridge.o
      Channel::queueMessage(char*) in cordova-bridge.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** ARCHIVE FAILED **

The following build commands failed:
	Ld /Users/sonder/Library/Developer/Xcode/DerivedData/HelloCordova-fqmhvsynhbqizkccpylpmwmahsxs/Build/Intermediates.noindex/ArchiveIntermediates/HelloCordova/IntermediateBuildFilesPath/HelloCordova.build/Debug-iphoneos/HelloCordova.build/Objects-normal/armv7/HelloCordova normal armv7
(1 failure)
Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/sonder/Desktop/mapbox/HelloCordova/platforms/ios/cordova/build-debug.xcconfig,-workspace,HelloCordova.xcworkspace,-scheme,HelloCordova,-configuration,Debug,-destination,generic/platform=iOS,-archivePath,HelloCordova.xcarchive,archive,CONFIGURATION_BUILD_DIR=/Users/sonder/Desktop/mapbox/HelloCordova/platforms/ios/build/device,SHARED_PRECOMPS_DIR=/Users/sonder/Desktop/mapbox/HelloCordova/platforms/ios/build/sharedpch

* **Version**:
* **Platform**:
* **Subsystem**:

**Comment by jaimecbernardo** [comment]
Hi @salihonder ,

nodejs-mobile only has support for arm64 CPUs, so for archiving you'd need to change the Deployment Target to 11.0, as that's the iOS version supported by the plugin: https://github.com/janeasystems/nodejs-mobile-cordova/tree/79092d967a1c6b35abd0f7b2f1dd436582f439ec#requirements

It can be done as mentioned in the README:
> Switch to Xcode:
>* select HelloCordova to view the project settings
>* in the General settings:
>  * in the Signing section select a team to sign the app
>  * in Deployment Info section select Deployment Target 11.0 or higher

Another way to achieve this would be setting the `deployment-target(string)` preference in your application's `config.xml`, as mentioned in the Cordova documentation: https://cordova.apache.org/docs/en/7.x/config_ref/index.html#preference

**Comment by salihonder** [comment]
It is fixed but now I got this error.

 export XCODE_PRODUCT_BUILD_VERSION=9F2000
    export XCODE_VERSION_ACTUAL=0941
    export XCODE_VERSION_MAJOR=0900
    export XCODE_VERSION_MINOR=0940
    export XPCSERVICES_FOLDER_PATH=HelloCordova.app/XPCServices
    export YACC=yacc
    export arch=arm64
    export diagnostic_message_length=80
    export variant=normal
    /bin/sh -c /Users/sonder/Library/Developer/Xcode/DerivedData/HelloCordova-fqmhvsynhbqizkccpylpmwmahsxs/Build/Intermediates.noindex/ArchiveIntermediates/HelloCordova/IntermediateBuildFilesPath/HelloCordova.build/Debug-iphoneos/HelloCordova.build/Script-BFD3730DA77345CA8828FDD7.sh
Skipping a ".node". Couldn't find a dynamically linked shared library inside /Users/sonder/Library/Developer/Xcode/DerivedData/HelloCordova-fqmhvsynhbqizkccpylpmwmahsxs/Build/Intermediates.noindex/ArchiveIntermediates/HelloCordova/InstallationBuildProductsLocation/Applications/HelloCordova.app/www/nodejs-project/node_modules/sqlite3/build/Release/.deps/Release/node_sqlite3.node
Found 2 valid frameworks and 1 invalid frameworks after rebuilding the native modules for iOS.
/Users/sonder/Desktop/mapbox/HelloCordova/Plugins/nodejs-mobile-cordova/install/helper-scripts/ios-create-plists-and-dlopen-override.js:116
  fs.copyFileSync(path.join(__dirname,'override-dlopen-paths-preload.js'),path.join(projectPath,'override-dlopen-paths-preload.js'));
     ^

TypeError: fs.copyFileSync is not a function
    at visitEveryFramework (/Users/sonder/Desktop/mapbox/HelloCordova/Plugins/nodejs-mobile-cordova/install/helper-scripts/ios-create-plists-and-dlopen-override.js:116:6)
    at Object.<anonymous> (/Users/sonder/Desktop/mapbox/HelloCordova/Plugins/nodejs-mobile-cordova/install/helper-scripts/ios-create-plists-and-dlopen-override.js:128:5)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
Command /bin/sh failed with exit code 1

** ARCHIVE FAILED **


The following build commands failed:
	PhaseScriptExecution Sign\ Node.js\ Mobile\ Native\ Modules /Users/sonder/Library/Developer/Xcode/DerivedData/HelloCordova-fqmhvsynhbqizkccpylpmwmahsxs/Build/Intermediates.noindex/ArchiveIntermediates/HelloCordova/IntermediateBuildFilesPath/HelloCordova.build/Debug-iphoneos/HelloCordova.build/Script-BFD3730DA77345CA8828FDD7.sh
(1 failure)
Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/sonder/Desktop/mapbox/HelloCordova/platforms/ios/cordova/build-debug.xcconfig,-workspace,HelloCordova.xcworkspace,-scheme,HelloCordova,-configuration,Debug,-destination,generic/platform=iOS,-archivePath,HelloCordova.xcarchive,archive,CONFIGURATION_BUILD_DIR=/Users/sonder/Desktop/mapbox/HelloCordova/platforms/ios/build/device,SHARED_PRECOMPS_DIR=/Users/sonder/Desktop/mapbox/HelloCordova/platforms/ios/build/sharedpch

**Comment by jaimecbernardo** [comment]
Hi @salihonder ,
We are using `fs.copyFileSync` inside a script needed for native modules support, but it seems this function is only available after node v8.5.0: https://nodejs.org/api/fs.html#fs_fs_copyfilesync_src_dest_flags

Updating your development machine's node runtime should fix this error.
