### ISSUE TITLE
dlopen failed: "....arm/libnodejs-mobile-react-native-native-lib.so" has bad ELF magic

### ISSUE THREAD

**Issue by nklhtv** [janeasystems/nodejs-mobile#139]
Project: nodejs-mobile-react-native
Version: 0.3.0
Mobile device: SM-T585
Mobile OS and version: Android 7.0
Development Node.js: 6.14.4
Development platform: ubuntu 18.04 LTS x64
NDK Version: r16b
react-native: 0.55.3

```
java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.stremio.beta-2/lib/arm/libnodejs-mobile-react-native-native-lib.so" has bad ELF magic
	at java.lang.Runtime.loadLibrary0(Runtime.java:977)
	at java.lang.System.loadLibrary(System.java:1567)
	at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobileModule.<clinit>(RNNodeJsMobileModule.java:57)
	at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobilePackage.createNativeModules(RNNodeJsMobilePackage.java:16)
	at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:106)
	at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1172)
	at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1142)
	at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1080)
	at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:113)
	at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:911)
	at java.lang.Thread.run(Thread.java:762)
```

I have this new crash in my crash reporting system that happend only with this device and this version of react-native-nodejs-mobile

**Comment by jaimecbernardo** [comment]
Hi @NikolaBorislavovHristov ,

Unfortunately I'm unable to verify the error in the specific device.

One possible thing you could try is updating the the NDK to r17b, since there was a similar `java.lang.UnsatisfiedLinkError` issue which was related to incompatibilities between applications and libraries built with with different NDK versions: https://github.com/janeasystems/nodejs-mobile/issues/81#issuecomment-406005676 

The library contained in `nodejs-mobile-react-native v0.3.0` is built with r17b.

Please let us know if this solves the issue.

**Comment by nklhtv** [comment]
@jaimecbernardo Thank you i will try
