### ISSUE TITLE
App getting crash on android sdk 19 using react native

### ISSUE THREAD

**Issue by hk4774** [janeasystems/nodejs-mobile#142]
* **Mobile device**: Android emulator 
* **Mobile OS and version**: 4.4, SDK version: 19
* **Development Node.js**: nodejs v8.5
* **Development platform**: macos 12.1

 java.lang.VerifyError: com/janeasystems/rn_nodejs_mobile/RNNodeJsMobileModule
                                                                                at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobilePackage.createNativeModules(RNNodeJsMobilePackage.java:16)
                                                                                at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:106)
                                                                                at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1171)
                                                                                at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1141)
                                                                                at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1083)
                                                                                at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:113)
                                                                                at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:920)
                                                                                at java.lang.Thread.run(Thread.java:841)

**Comment by jaimecbernardo** [comment]
Hi @hk4774 ,
Do you have some replication steps or a repo where the error is reproducible?
Thank you.

**Comment by hk4774** [comment]
STR:- Just use the steps to setup the project as mentioned in the wiki(for react-native). Run the app from command line or from the android studio on the android emulator which should be running on sdk 19. You will see the crash on the device and will get error log mentioned in the issue.

Thanks for the response.

**Comment by jaimecbernardo** [comment]
Hi @hk4774 ,
Sorry, just noticed that you were running on SDK 19. The minimum version is API 21.
Here's a related issue about this: https://github.com/janeasystems/nodejs-mobile/issues/103

The core library is built for API 21 and the react-native plugin uses `os.setEnv()`, which wasn't added until API 21, and that's what causes the `java.lang.VerifyError`.

**Comment by hk4774** [comment]
Hi @jaimecbernardo, thanks for the reply. Got the issue here. but can't we use [ProcessBuilder](https://developer.android.com/reference/java/lang/ProcessBuilder) for this? for eg. we can set the environment like this: 

```
String path = System.getenv("HOME");

ProcessBuilder pb = new ProcessBuilder("/bin/bash","-c","export PATH=" +
    "PATH-TO-ADD" + ":" + path + " && exec");
```

So by doing this, can't we back port this to below 21 as ProcessBuilder was added at API level 1?

**Comment by jaimecbernardo** [comment]
Hi @hk4774 , You'd still need to recompile the core library to support API 19, as discussed in the issue I've linked: https://github.com/janeasystems/nodejs-mobile/issues/103
We're open to pull requests for supporting this scenario.

**Comment by hk4774** [comment]
@jaimecbernardo Okay man. I'm closing this issue. I'll try to build this library to support below 21 with necessary changes. I'll update on this on the #103 thread.

Once again. Thanks for the responses.
