### ISSUE TITLE
Error in building Cordova/Usenatives - How to use the nodejs-mobile lib?

### ISSUE THREAD

**Issue by paramtatv** [janeasystems/nodejs-mobile#149]
I tried to build the cordova/Ussenatives. But I get the following error. Looks like sha3 needs some v8 lib in node installation. What is the role of building nodejs-mobile in these projects. How to add them to the path?

```
ubuntu@Yoga:~/nodejs-mobile-samples/cordova/UseNativeModules$ npm run prepare-nodejs

> com.example.usenativemodules@1.0.0 prepare-nodejs /home/ubuntu/nodejs-mobile-samples/cordova/UseNativeModules
> cd www/nodejs-project && npm install


> sha3@1.2.2 install /home/ubuntu/nodejs-mobile-samples/cordova/UseNativeModules/www/nodejs-project/node_modules/sha3
> node-gyp rebuild

make: Entering directory `/home/ubuntu/nodejs-mobile-samples/cordova/UseNativeModules/www/nodejs-project/node_modules/sha3/build'
  CXX(target) Release/obj.target/sha3/src/addon.o
In file included from ../src/addon.cpp:1:
In file included from /home/ubuntu/.node-gyp/11.4.0/include/node/node.h:63:
/home/ubuntu/.node-gyp/11.4.0/include/node/v8.h:21:10: fatal error: 'memory' file not found
#include <memory>
         ^~~~~~~~
1 error generated.
make: *** [Release/obj.target/sha3/src/addon.o] Error 1
make: Leaving directory `/home/ubuntu/nodejs-mobile-samples/cordova/UseNativeModules/www/nodejs-project/node_modules/sha3/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Linux 4.15.0-42-generic
gyp ERR! command "/home/ubuntu/nodejs-mobile-samples/cordova/UseNativeModules/node_modules/node/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ubuntu/nodejs-mobile-samples/cordova/UseNativeModules/www/nodejs-project/node_modules/sha3
gyp ERR! node -v v11.4.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN nodejs-mobile-use-native-modules-project@0.1.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sha3@1.2.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sha3@1.2.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2018-12-10T18_50_28_414Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! com.example.usenativemodules@1.0.0 prepare-nodejs: `cd www/nodejs-project && npm install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the com.example.usenativemodules@1.0.0 prepare-nodejs script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2018-12-10T18_50_28_434Z-debug.log
ubuntu@Yoga:~/nodejs-mobile-samples/cordova/UseNativeModules$ 

```

**Comment by jaimecbernardo** [comment]
The ability to compile native modules in the development machine is needed. You seem to have figured it out.
