### ISSUE TITLE
Possible Bug: BuildNpmModules starts before CopyNodeProjectAssets 

### ISSUE THREAD

**Issue by paramtatv** [janeasystems/nodejs-mobile#150]
There is a possible gradle bug or my lack of knowledge( :) ) about it. When I build the Usenatives repo from cordova sample, it generates the BuildNpmModulesarmeabi-v7a error. And the error trace points to missing folder of 'node-project' in build directory. The gradle code has a dependsOn based sequence where Copy must finish before build. But somehow that is not happening. 
This might be due to many reasons, but I suspect that gradle is not honoring the dependsOn and doLast for waiting till finish.
Please help.

------------------------------------------------------------
Gradle 2.10
------------------------------------------------------------

Build time:   2016-01-26 15:17:49 UTC
Build number: none
Revision:     UNKNOWN

Groovy:       2.4.5
Ant:          Apache Ant(TM) version 1.9.6 compiled on July 20 2018
JVM:          1.8.0_191 (Oracle Corporation 25.191-b12)
OS:           Linux 4.15.0-42-generic amd64

`
ANDROID_HOME=/home/ubuntu/Android/Sdk
JAVA_HOME=/usr/lib/jvm/java-8-oracle
Subproject Path: CordovaLib
publishNonDefault is deprecated and has no effect anymore. All variants are now published.
:CopyNodeProjectAssetsarmeabi-v7a
:MakeToolchainarmeabi-v7a
HOST_OS=linux
HOST_EXE=
HOST_ARCH=x86_64
HOST_TAG=linux-x86_64
HOST_NUM_CPUS=8
BUILD_NUM_CPUS=16
Toolchain installed to /home/ubuntu/nodejs-mobile-samples/cordova/UseNativeModules/platforms/android/build/standalone-toolchains/arm-linux-androideabi.
:BuildNpmModulesarmeabi-v7a FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':BuildNpmModulesarmeabi-v7a'.
> A problem occurred starting process 'command 'npm''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.6/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 4s
3 actionable tasks: 3 executed
/home/ubuntu/nodejs-mobile-samples/cordova/UseNativeModules/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':BuildNpmModulesarmeabi-v7a'.
> A problem occurred starting process 'command 'npm''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s

`

# Android Studio Log
`
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':BuildNpmModulesarmeabi-v7a'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:103)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:73)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:256)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:249)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:238)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:663)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:597)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.gradle.process.internal.ExecException: A problem occurred starting process 'command 'npm''
	at org.gradle.process.internal.DefaultExecHandle.execExceptionFor(DefaultExecHandle.java:226)
	at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:204)
	at org.gradle.process.internal.DefaultExecHandle.failed(DefaultExecHandle.java:349)
	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:85)
	at org.gradle.internal.operations.BuildOperationIdentifierPreservingRunnable.run(BuildOperationIdentifierPreservingRunnable.java:39)
	... 6 more
Caused by: net.rubygrapefruit.platform.NativeException: Could not start 'npm'
	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:27)
	at net.rubygrapefruit.platform.internal.WrapperProcessLauncher.start(WrapperProcessLauncher.java:36)
	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:67)
	... 7 more
Caused by: java.io.IOException: Cannot run program "npm" (in directory "/home/ubuntu/nodejs-mobile-samples/cordova/UseNativeModules/platforms/android/build/nodejs-native-assets-temp-build/nodejs-native-assets-armeabi-v7a/nodejs-project"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
	... 9 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 10 more

`

**Comment by paramtatv** [comment]
Here is my 2 cents for Copy task which works. I am 1/10 in gradle so please apply your own logic.
```
task "CopyNodeProjectAssets${abi_name}" (type: Copy){
            description = "Copying node assets to build native modules for ${abi_name}."
            /*
            inputs.files fileTree (
                    dir: "${project.projectDir}/assets/www/nodejs-project/"
                ).exclude({
                    details -> // We shouldn't need to rebuild native code if there are only changes in the Node.js project javascript files.
                        !details.isDirectory() &&
                        details.getPath().endsWith('.js') &&
                        !details.getPath().startsWith('node_modules/')
                })
            outputs.file "${rootProject.buildDir}/nodejs-native-assets-temp-build/nodejs-native-assets-${abi_name}/copy.timestamp"
            doLast {
              */
                delete "${rootProject.buildDir}/nodejs-native-assets-temp-build/nodejs-native-assets-${abi_name}/"
                //copy {
                    from "${project.projectDir}/assets/www/nodejs-project/"
                    into "${rootProject.buildDir}/nodejs-native-assets-temp-build/nodejs-native-assets-${abi_name}/nodejs-project/"
                    // Symlinks to binaries are resolved by cordova prepare and Gradle during the copy, causing build time errors.
                    // The original project's .bin folder will be added to the path while building in the BuildNpmModules tasks.
                    exclude "**/.bin"
                //}
                if (OperatingSystem.current().isMacOsX()) {
                    // Copy the helper script for calling npm when building in Android Studio on macOS.
                    copy {
                        from "${project.projectDir}/assets/www/build-native-modules-MacOS-helper-script.sh"
                        into "${rootProject.buildDir}/nodejs-native-assets-temp-build/nodejs-native-assets-${abi_name}/"
                    }
                }
                outputs.file "${rootProject.buildDir}/nodejs-native-assets-temp-build/nodejs-native-assets-${abi_name}/copy.timestamp"

                new File("copy.timestamp").text = "${new Date().format('yyyy-MM-dd HH:mm:ss')}"
            //}
        }
```

**Comment by jaimecbernardo** [comment]
Hi @tim-coin , The error is this:
```
Cannot run program "npm" (in directory "/home/ubuntu/nodejs-mobile-samples/cordova/UseNativeModules/platforms/android/build/nodejs-native-assets-temp-build/nodejs-native-assets-armeabi-v7a/nodejs-project"): error=2, No such file or directory
```
I suspect that the Android build process is unable to find `npm` in the PATH, and that's why you're getting this error. (The error thrown from the Java side can be hard to interpret)

Your proposed fix means that the native modules won't be rebuilt for Android and as such they won't work when trying to run the application.

**Comment by paramtatv** [comment]
No. The log says clearly this. Closing the issue now.  The solution works, for anyone who may need.

`
Caused by: java.io.IOException: Cannot run program "npm" (in directory "/home/ubuntu/nodejs-mobile-samples/cordova/UseNativeModules/platforms/android/build/nodejs-native-assets-temp-build/nodejs-native-assets-armeabi-v7a/nodejs-project"): error=2, No such file or directory`

**Comment by chiemekailo** [comment]
> Here is my 2 cents for Copy task which works. I am 1/10 in gradle so please apply your own logic.
> 
> ```
> task "CopyNodeProjectAssets${abi_name}" (type: Copy){
>             description = "Copying node assets to build native modules for ${abi_name}."
>             /*
>             inputs.files fileTree (
>                     dir: "${project.projectDir}/assets/www/nodejs-project/"
>                 ).exclude({
>                     details -> // We shouldn't need to rebuild native code if there are only changes in the Node.js project javascript files.
>                         !details.isDirectory() &&
>                         details.getPath().endsWith('.js') &&
>                         !details.getPath().startsWith('node_modules/')
>                 })
>             outputs.file "${rootProject.buildDir}/nodejs-native-assets-temp-build/nodejs-native-assets-${abi_name}/copy.timestamp"
>             doLast {
>               */
>                 delete "${rootProject.buildDir}/nodejs-native-assets-temp-build/nodejs-native-assets-${abi_name}/"
>                 //copy {
>                     from "${project.projectDir}/assets/www/nodejs-project/"
>                     into "${rootProject.buildDir}/nodejs-native-assets-temp-build/nodejs-native-assets-${abi_name}/nodejs-project/"
>                     // Symlinks to binaries are resolved by cordova prepare and Gradle during the copy, causing build time errors.
>                     // The original project's .bin folder will be added to the path while building in the BuildNpmModules tasks.
>                     exclude "**/.bin"
>                 //}
>                 if (OperatingSystem.current().isMacOsX()) {
>                     // Copy the helper script for calling npm when building in Android Studio on macOS.
>                     copy {
>                         from "${project.projectDir}/assets/www/build-native-modules-MacOS-helper-script.sh"
>                         into "${rootProject.buildDir}/nodejs-native-assets-temp-build/nodejs-native-assets-${abi_name}/"
>                     }
>                 }
>                 outputs.file "${rootProject.buildDir}/nodejs-native-assets-temp-build/nodejs-native-assets-${abi_name}/copy.timestamp"
> 
>                 new File("copy.timestamp").text = "${new Date().format('yyyy-MM-dd HH:mm:ss')}"
>             //}
>         }
> ```

@tim-coin were do i place the code before running "$ cordova build android"?
