### ISSUE TITLE
build failure for Raspberry Pi

### ISSUE THREAD

**Issue by pgupta408** [janeasystems/nodejs-mobile#176]
* **Project**: nodejs-mobile
* **Version**: latest
* **Mobile device**:  Raspberry Pi
* **Mobile OS and version**:  Raspian (Debian) Linux  4.14.79-v7+ #1159
* **Development Node.js**: v8.15.0
* **Development platform**:  

pi@gateway:~/nodejs-mobile $ ./tools/android_build.sh ~/android-ndk-r18b
rm -f -r out/Makefile node node_g out/Release/node \
                out/Release/node.exp
rm -f -r node_modules
rm -f test.tap
HOST_OS=linux
HOST_EXE=
HOST_ARCH=x86_64
HOST_TAG=linux-x86_64
HOST_NUM_CPUS=4
BUILD_NUM_CPUS=8
Toolchain installed to /home/pi/nodejs-mobile/android-toolchain.
Traceback (most recent call last):
  File "./configure", line 45, in <module>
    from gyp.common import GetFlavor
  File "./tools/gyp/pylib/gyp/__init__.py", line 8, in <module>
    import gyp.input
  File "./tools/gyp/pylib/gyp/input.py", line 5, in <module>
    from compiler.ast import Const
  File "/home/pi/nodejs-mobile/android-toolchain/lib/python2.7/compiler/__init__.py", line 29, in <module>
    from compiler.transformer import parse, parseFile
  File "/home/pi/nodejs-mobile/android-toolchain/lib/python2.7/compiler/transformer.py", line 29, in <module>
    import parser
ImportError: /home/pi/nodejs-mobile/android-toolchain/lib/python2.7/lib-dynload/parser.so: wrong ELF class: ELFCLASS64
pi@gateway:~/nodejs-mobile $

**Comment by jaimecbernardo** [comment]
Hi @pgupta408,

Haven't tried building nodejs-mobile in a Raspberry Pi yet, and I'm not sure if that would work, but from the messages pasted I'm guessing you're trying to run an Android NDK that's built for x86_64 CPUS. You'd have to use a NDK that would work for the Raspberry Pi.

**Comment by pgupta408** [comment]
Your documentation says that you support ARM as well. So, during build process, configuration parameters must be generated based on platform used for build.

I am try to build directly on Raspberry Pi. 

Thanks

On Mar 14, 2019, at 8:20 AM, Jaime Bernardo <notifications@github.com> wrote:

Hi @pgupta408,

Haven't tried building nodejs-mobile in a Raspberry Pi yet, and I'm not sure if that would work, but from the messages pasted I'm guessing you're trying to run an Android NDK that's built for x86_64 CPUS. You'd have to use a NDK that would work for the Raspberry Pi.

**Comment by jaimecbernardo** [comment]
We support running on Android ARM.
Building in a ARM development machine hasn't been tested.

Are you able to build Android applications on the Raspberry Pi using the same Android NDK?
From the output, I think that Android NDK shouldn't be the one used to build on a ARM system.
