### ISSUE TITLE
Error while importing the packages?

### ISSUE THREAD

**Issue by vedant-dobby** [janeasystems/nodejs-mobile#223]
* **Project**: Dobby Automations
* **Version**: 0.0.1
* **Mobile device**: OnePlus 5
* **Mobile OS and version**: Android 9
* **Development Node.js**: 
* **Development platform**: React-Native

I am trying to run the following code

```
 var rn_bridge = require('rn-bridge');
// Echo every message received from react-native.

function apiCall (callback) {
var Protocol = require('azure-iot-device-mqtt').Mqtt;
var Client = require('azure-iot-device').Client;
var Message = require('azure-iot-device').Message;
var iotData = ''

var connectionString = 'can't reveal the access key';

var client = Client.fromConnectionString(connectionString, Protocol);

var connectCallback = function (err) {
  if (err) {
    console.error('Could not connect: ' + err.message);
  } else {
    // console.log('Client connected');
    client.on('message', function (msg) {

      iotData = msg.data.toString('utf8')
      callback(iotData)
    })

      var date = new Date();
      var timestamp = date.getTime();
      var data = JSON.stringify({"data":{"Status":1}, "toDevice":"iot-cbf434d6", "fromDevice":"vedantPhone",'timestamp':timestamp});
      var message = new Message(data);
      console.log('Sending message: ' + message.getData());
      client.sendEvent(message);


    client.on('error', function (err) {
      console.error(err.message);
    });

    client.on('disconnect', function () {
      client.removeAllListeners();
    });
  }
}
function test (callback) {
  callback('Call back is fine')
}

client.open(connectCallback);
// return iotData
}

rn_bridge.channel.on('message', (messageData) => {

})

apiCall(data => {
   rn_bridge.channel.send(data)
})
```

The application is crashing. 
When I did adb logcat, this what I got.

```
08-21 13:26:36.053  3619  3686 E AndroidRuntime: FATAL EXCEPTION: Thread-3
08-21 13:26:36.053  3619  3686 E AndroidRuntime: Process: com.dobbyautomations, PID: 3619
08-21 13:26:36.053  3619  3686 E AndroidRuntime: java.lang.RuntimeException: Node assets copy failed
08-21 13:26:36.053  3619  3686 E AndroidRuntime: 	at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobileModule$1.run(RNNodeJsMobileModule.java:106)
08-21 13:26:36.053  3619  3686 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
08-21 13:26:36.053  3619  3686 E AndroidRuntime: Caused by: java.io.FileNotFoundException: nodejs-project/node_modules/type/test/_lib/class-if-supported.js
08-21 13:26:36.053  3619  3686 E AndroidRuntime: 	at android.content.res.AssetManager.nativeOpenAsset(Native Method)
08-21 13:26:36.053  3619  3686 E AndroidRuntime: 	at android.content.res.AssetManager.open(AssetManager.java:755)
08-21 13:26:36.053  3619  3686 E AndroidRuntime: 	at android.content.res.AssetManager.open(AssetManager.java:732)
08-21 13:26:36.053  3619  3686 E AndroidRuntime: 	at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobileModule.copyAsset(RNNodeJsMobileModule.java:431)
08-21 13:26:36.053  3619  3686 E AndroidRuntime: 	at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobileModule.copyNodeJsAssets(RNNodeJsMobileModule.java:371)
08-21 13:26:36.053  3619  3686 E AndroidRuntime: 	at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobileModule.access$100(RNNodeJsMobileModule.java:30)
08-21 13:26:36.053  3619  3686 E AndroidRuntime: 	at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobileModule$1.run(RNNodeJsMobileModule.java:103)
08-21 13:26:36.053  3619  3686 E AndroidRuntime: 	... 1 more
08-21 13:36:27.054  6108  6210 E AndroidRuntime: FATAL EXCEPTION: Thread-3
08-21 13:36:27.054  6108  6210 E AndroidRuntime: Process: com.dobbyautomations, PID: 6108
08-21 13:36:27.054  6108  6210 E AndroidRuntime: java.lang.RuntimeException: Node assets copy failed
08-21 13:36:27.054  6108  6210 E AndroidRuntime: 	at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobileModule$1.run(RNNodeJsMobileModule.java:106)
08-21 13:36:27.054  6108  6210 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
08-21 13:36:27.054  6108  6210 E AndroidRuntime: Caused by: java.io.FileNotFoundException: nodejs-project/node_modules/type/test/_lib/class-if-supported.js
08-21 13:36:27.054  6108  6210 E AndroidRuntime: 	at android.content.res.AssetManager.nativeOpenAsset(Native Method)
08-21 13:36:27.054  6108  6210 E AndroidRuntime: 	at android.content.res.AssetManager.open(AssetManager.java:755)
08-21 13:36:27.054  6108  6210 E AndroidRuntime: 	at android.content.res.AssetManager.open(AssetManager.java:732)
08-21 13:36:27.054  6108  6210 E AndroidRuntime: 	at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobileModule.copyAsset(RNNodeJsMobileModule.java:431)
08-21 13:36:27.054  6108  6210 E AndroidRuntime: 	at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobileModule.copyNodeJsAssets(RNNodeJsMobileModule.java:371)
08-21 13:36:27.054  6108  6210 E AndroidRuntime: 	at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobileModule.access$100(RNNodeJsMobileModule.java:30)
08-21 13:36:27.054  6108  6210 E AndroidRuntime: 	at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobileModule$1.run(RNNodeJsMobileModule.java:103)
08-21 13:36:27.054  6108  6210 E AndroidRuntime: 	... 1 more
08-21 13:36:27.066  6108  6236 D OSTracker: OS Event: crash
```

This is my package.json

```
{
  "//": [
    "Rename this sample file to package.json to use on your project.",
    "The sample-package.json file will be overwritten in updates/reinstalls."
  ],
  "name": "DobbyAutomations",
  "version": "0.0.1",
  "description": "node part of the project",
  "main": "main.js",
  "author": "janeasystems",
  "license": "",
  "dependencies": {
    "azure-iot-common": "^1.10.1",
    "azure-iot-device": "^1.11.0",
    "azure-iot-device-mqtt": "^1.10.1",
    "type": "^1.0.3"
  }
}
```

I did npm install and node_modules folder is present. What could be going wrong and how to fix it?
@jaimecbernardo

**Comment by jaimecbernardo** [comment]
Hi @vedant-dobby ,

This is most likely caused by the folder starting with underscore (`nodejs-project/node_modules/type/test/_lib`). The Android packager ignores folders starting with underscore by default and won't package them.

Try following the instructions in this issue:
https://github.com/JaneaSystems/nodejs-mobile/issues/60

**Comment by vedant-dobby** [comment]
Thanks @jaimecbernardo  It worked. But if I install it on some other computer I would have to repeat the same thing again. Is there a fix for that?

**Comment by jaimecbernardo** [comment]
Hi @vedant-dobby ,
There's still not a permanent fix as of this time, as discussed in the sibling issue:
> While one of the gradle files involved in the workaround is inside the plugin, the application gradle file is created by react-native, so we'll still have to look for a more permanent solution that doesn't involve editing that file manually.

Also, the default Android behavior is valid for other projects.

**Comment by vedant-dobby** [comment]
@jaimecbernardo Thanks for the update
