### ISSUE TITLE
"Unable to graft xml at selector" when installing nodejs-mobile-cordova

### ISSUE THREAD

**Issue by dr-nyt** [janeasystems/nodejs-mobile#238]
* **Project**:
nodejs-mobile-cordova
* **Version**:
0.3.4
* **Mobile device**:
N/A
* **Mobile OS and version**:
N/A
* **Development Node.js**:
v10.16.1
* **Development platform**:
64-bit Windows 10

When I try to install this plugin in a fresh cordova project `cordova plugin add nodejs-mobile-cordova`, I get the following error:
```
Installing "nodejs-mobile-cordova" for android
Failed to install 'nodejs-mobile-cordova': Error: Unable to graft xml at selector "/manifest/uses-sdk" from "A:\Github Repos\App-Mobile\app\platforms\android\app\src\main\AndroidManifest.xml" during config install
    at ConfigFile_graft_child [as graft_child] (A:\Github Repos\App-Mobile\app\node_modules\cordova-common\src\ConfigChanges\ConfigFile.js:120:19)
    at PlatformMunger_apply_file_munge [as apply_file_munge] (A:\Github Repos\App-Mobile\app\node_modules\cordova-common\src\ConfigChanges\ConfigChanges.js:81:34)
    at munge_helper (A:\Github Repos\App-Mobile\app\node_modules\cordova-common\src\ConfigChanges\ConfigChanges.js:238:14)
    at PlatformMunger.add_plugin_changes (A:\Github Repos\App-Mobile\app\node_modules\cordova-common\src\ConfigChanges\ConfigChanges.js:159:12)
    at A:\Github Repos\App-Mobile\app\node_modules\cordova-common\src\PluginManager.js:123:29
    at _fulfilled (A:\Github Repos\App-Mobile\app\node_modules\q\q.js:854:54)
    at A:\Github Repos\App-Mobile\app\node_modules\q\q.js:883:30
    at Promise.promise.promiseDispatch (A:\Github Repos\App-Mobile\app\node_modules\q\q.js:816:13)
    at A:\Github Repos\App-Mobile\app\node_modules\q\q.js:877:14
    at runSingle (A:\Github Repos\App-Mobile\app\node_modules\q\q.js:137:13)
Unable to graft xml at selector "/manifest/uses-sdk" from "A:\Github Repos\App-Mobile\app\platforms\android\app\src\main\AndroidManifest.xml" during config install
```

**Comment by thepragmaticdev** [comment]
@dr-nyt Try deleting spaces from path. This solved the issue for me.

**Comment by dr-nyt** [comment]
> @dr-nyt Try deleting spaces from path. This solved the issue for me.

I'm with react native now but this is probably the right answer for anyone still looking

**Comment by JaosnHsieh** [comment]
> @dr-nyt Try deleting spaces from path. This solved the issue for me.

can i know which files or command to delete?

i tried to delete spaces in `platforms/android/app/src/main/AndroidManifest.xml` but didn't work

**Comment by dr-nyt** [comment]
@JaosnHsieh No, don't delete the manifest file. The folder my project was stored in was:

C:\Github Repos\App-Mobile\

The problem is that there is a space in the "Github Repos" folder name so we change the folder name to "GithubRepos" instead. So my path should look like this:

C:\GithubRepos\App-Mobile\app\

Basically ur folders shouldnt have spaces in their names

**Comment by rossmarinaro** [comment]
that didnt work for me. i still get the same message
