### ISSUE TITLE
jest-haste-map: Haste module naming collision - nodejs-mobile-react-native

### ISSUE THREAD

**Issue by emclab** [janeasystems/nodejs-mobile#244]
* **Project**: nodejs-mobile-react-native
* **Version**:0.40.0
* **Mobile device**:android
* **Mobile OS and version**:win10
* **Development Node.js**:10.16.0
* **Development platform**:VS code
React Native: 0.61.5

After renaming `sample-package.json` to `package.json`, there is an error below. There are quite a few posts online about the similar error, but none of them seem works in my case. 

Loading dependency graph...jest-haste-map: Haste module naming collision: sample-node-project
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>\nodejs-assets\nodejs-project\package.json
    * <rootDir>\android\build\nodejs-assets\nodejs-project\package.json

Failed to construct transformer:  { Error: Duplicated files or mocks. Please check the console for more info
    at setModule (C:\D\code\js\ipat_testmbrn\node_modules\metro\node_modules\jest-haste-map\build\index.js:620:17)
    at workerReply (C:\D\code\js\ipat_testmbrn\node_modules\metro\node_modules\jest-haste-map\build\index.js:691:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  mockPath1: 'nodejs-assets\\nodejs-project\\package.json',
  mockPath2:
   'android\\build\\nodejs-assets\\nodejs-project\\package.json' }
(node:17916) UnhandledPromiseRejectionWarning: Error: Duplicated files or mocks. Please check the console for more info
    at setModule (C:\D\code\js\ipat_testmbrn\node_modules\metro\node_modules\jest-haste-map\build\index.js:620:17)
    at workerReply (C:\D\code\js\ipat_testmbrn\node_modules\metro\node_modules\jest-haste-map\build\index.js:691:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:17916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17916) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
::ffff:127.0.0.1 - - [31/Jan/2020:21:33:32 +0000] "GET /index.bundle?platform=android&dev=true&minify=false HTTP/1.1" 500 535 "-" "okhttp/3.12.1"
Error: Duplicated files or mocks. Please check the console for more info
    at setModule (C:\D\code\js\ipat_testmbrn\node_modules\metro\node_modules\jest-haste-map\build\index.js:620:17)
    at workerReply (C:\D\code\js\ipat_testmbrn\node_modules\metro\node_modules\jest-haste-map\build\index.js:691:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by chiragshah1312** [comment]
what's the solution to this? @emclab

**Comment by allforabit** [comment]
I think it's the solution in this issue: https://github.com/JaneaSystems/nodejs-mobile/issues/34
