### ISSUE TITLE
[iOS] BigInt is not defined

### ISSUE THREAD

**Issue by petergaultney** [janeasystems/nodejs-mobile#250]
Project:  nodejs-mobile-react-native
Version: 0.5.0
Mobile device: iPhone xR Simulator; iOS 12.4
Mobile OS and version: iOS 12.4
Development Node.js: 12.14.1
Development platform: Darwin psg-mbp32.local 18.7.0 Darwin Kernel Version 18.7.0: Sun Dec  1 18:59:03 PST 2019; root:xnu-4903.278.19~1/RELEASE_X86_64 x86_64

React Native: 0.60.5

```
ReferenceError: 'BigInt' is not defined
   at Anonymous function (/Users/<myuser>/Library/Developer/CoreSimulator/Devices/FE11A260-BC1A-421F-921D-066D3625B0A5/data/Containers/Bundle/Application/7B255216-301B-49D6-A086-1EE19D0DDFE1/<appname>.app/nodejs-project/node_modules/bigint-crypto-utils/dist/bigint-crypto-utils-latest.node.js:5:1)
   at Module.prototype._compile (internal/modules/cjs/loader.js:688:5)
   at Module._extensions[.js] (internal/modules/cjs/loader.js:699:3)
   at Module.prototype.load (internal/modules/cjs/loader.js:598:3)
   at tryModuleLoad (internal/modules/cjs/loader.js:537:5)
   at Module._load (internal/modules/cjs/loader.js:529:3)
   at Module.prototype.require (internal/modules/cjs/loader.js:636:3)
   at require (internal/modules/cjs/helpers.js:20:7)
```

Is this a known issue with the chakracore-based Node runtime for iOS? Is there any way to get BigInt defined on iOS?

**Comment by jaimecbernardo** [comment]
Hi @petergaultney ,
It's possible this was not implemented on ChakraCore. Please give it a try on `nodejs-mobile-react-native` version `0.6.0`, which runs V8 on iOS.
