### ISSUE TITLE
armeabi-v7a already exists

### ISSUE THREAD

**Issue by Rudimo** [janeasystems/nodejs-mobile#31]
* **nodejs-mobile-cordova 0.1.2**:
* **macOS High Sierra 10.13.2**:

Hello guys. I develop application on the ionic 3. I use **cordova-sqlite-storage** plugin. Then I run `ionic cordova build android`, I get error:

```sh
Failed to install 'nodejs-mobile-cordova': CordovaError: Uh oh!
"/Users/rudimo/projects/my/testapp/platforms/android/libs/armeabi-v7a" already exists!
    at copyNewFile (/Users/rudimo/projects/my/testapp/platforms/android/cordova/lib/pluginHandlers.js:245:45)
    at install (/Users/rudimo/projects/my/testapp/platforms/android/cordova/lib/pluginHandlers.js:43:17)
    at ActionStack.process (/Users/rudimo/projects/my/testapp/platforms/android/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/Users/rudimo/projects/my/testapp/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:114:20)
    at PluginManager.addPlugin (/Users/rudimo/projects/my/testapp/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:144:17)
    at /Users/rudimo/projects/my/testapp/platforms/android/cordova/Api.js:243:74
    at _fulfilled (/Users/rudimo/projects/my/testapp/platforms/android/cordova/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/Users/rudimo/projects/my/testapp/platforms/android/cordova/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/Users/rudimo/projects/my/testapp/platforms/android/cordova/node_modules/q/q.js:816:13)
    at /Users/rudimo/projects/my/testapp/platforms/android/cordova/node_modules/q/q.js:570:49

Failed to restore plugin "nodejs-mobile-cordova" from config.xml. You might need to try adding it again. Error: Uh oh!
"/Users/rudimo/projects/my/testapp/platforms/android/libs/armeabi-v7a" already exists!
```
How to build it?
Thank you.

**Comment by jaimecbernardo** [comment]
Hi @Rudimo , Thank you for the issue.

We're not familiar with Ionic and we were unaware that you could use Cordova plugins in it.

Would you mind sharing a repo / instructions on how to replicate it? We could also do it in the community chat: https://gitter.im/nodejs-mobile/community

Thank you, in advance.

**Comment by Rudimo** [comment]
@jaimecbernardo Thank you.

**I changed reorder the plugins**. And it success build.
My test repository: https://github.com/Rudimo/ionic-nodejs-mobile-cordova
