### ISSUE TITLE
Node assets copy failed : caused by builtin_modules

### ISSUE THREAD

**Issue by frankyfdr** [janeasystems/nodejs-mobile#318]
Hi, I am facing problems to build the react native project for android, on iOS works fine.
on the android simulator and android devices. I am facing those errors

I am using the nodes-mobile-react-native version 0.5.0 because of issues in the latest version

I have add the following as suggested in
[https://github.com/JaneaSystems/nodejs-mobile/issues/60](url)
```
  aaptOptions {
            ignoreAssetsPattern '!.svn:!.git:!.ds_store:!*.scc:!CVS:!thumbs.db:!picasa.ini:!*~'
            
        }
```

and not works

I am using an MacIOS, 

Android studio Loggat output

2021-05-14 12:45:43.311 7290-7691/com.mobileapp E/AndroidRuntime: FATAL EXCEPTION: Thread-2
    Process: com.mobileapp, PID: 7290
    java.lang.RuntimeException: Node assets copy failed
        at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobileModule$1.run(RNNodeJsMobileModule.java:106)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.io.FileNotFoundException: builtin_modules
        at android.content.res.AssetManager.nativeOpenAsset(Native Method)
        at android.content.res.AssetManager.open(AssetManager.java:957)
        at android.content.res.AssetManager.open(AssetManager.java:934)
        at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobileModule.copyAsset(RNNodeJsMobileModule.java:431)
        at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobileModule.copyAssetFolder(RNNodeJsMobileModule.java:420)
        at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobileModule.copyNodeJsAssets(RNNodeJsMobileModule.java:388)
        at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobileModule.access$100(RNNodeJsMobileModule.java:30)
        at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobileModule$1.run(RNNodeJsMobileModule.java:103)
        at java.lang.Thread.run(Thread.java:923) 

RNNodeJsMobileModule

line 388

` copyAssetFolder("node_modules", builtinModulesPath);`

the app crash on this line

any idea how to fix it?

**Comment by frankyfdr** [comment]
fixed by removing sourceset {} on gradle
