### ISSUE TITLE
Fail compiling Android Cordova Project using node.js-mobile-cordova plugin.

### ISSUE THREAD

**Issue by kledsonzg** [janeasystems/nodejs-mobile#358]
Hi!

I'm attempting to compile the Cordova project using node.js-mobile-cordova, and the output is as follows:

```
PS W:\Programming\Web Apps\Mais Entregas Para Motoristas\MaisEntregas> cordova build android -verbose
No scripts found for hook "before_build".
No scripts found for hook "before_prepare".
Checking for saved platforms that haven't been added to the project
Loaded API for android project W:\Programming\Web Apps\Mais Entregas Para Motoristas\MaisEntregas\platforms\android\cordova\Api.js
Checking for saved plugins that haven't been added to the project
Generating platform-specific config.xml from defaults for android at W:\Programming\Web Apps\Mais Entregas Para Motoristas\MaisEntregas\platforms\android\app\src\main\res\xml\config.xml
Merging project's config.xml into platform-specific android config.xml
[Gradle Properties] Preparing Configuration
[Gradle Properties] Appending default configuration properties
[Gradle Properties] Appending custom configuration properties
[Gradle Properties] Updating and Saving File
Merging and updating files from [www, platforms\android\platform_www] to platforms\android\app\src\main\assets\www
  copy  www\config\json\db_config.json platforms\android\app\src\main\assets\www\config\json\db_config.json (updated file)
  copy  platforms\android\platform_www\cordova.js platforms\android\app\src\main\assets\www\cordova.js (updated file)
  copy  platforms\android\platform_www\cordova_plugins.js platforms\android\app\src\main\assets\www\cordova_plugins.js (updated file)
  copy  www\css\index.css platforms\android\app\src\main\assets\www\css\index.css (updated file)
  copy  www\css\login.css platforms\android\app\src\main\assets\www\css\login.css (updated file)
  copy  www\css\signature.css platforms\android\app\src\main\assets\www\css\signature.css (updated file)
  copy  www\html\login.html platforms\android\app\src\main\assets\www\html\login.html (updated file)
  copy  www\img\customizable-icon.png platforms\android\app\src\main\assets\www\img\customizable-icon.png (updated file)
  copy  www\img\github-icon-hover.png platforms\android\app\src\main\assets\www\img\github-icon-hover.png (updated file)
  copy  www\img\github-icon.png platforms\android\app\src\main\assets\www\img\github-icon.png (updated file)
  copy  www\img\mais-entregas.png platforms\android\app\src\main\assets\www\img\mais-entregas.png (updated file)
  copy  www\img\next-arrow-icon.png platforms\android\app\src\main\assets\www\img\next-arrow-icon.png (updated file)
  copy  www\img\truck-interior.jpg platforms\android\app\src\main\assets\www\img\truck-interior.jpg (updated file)
  copy  www\img\white-customizable-icon.png platforms\android\app\src\main\assets\www\img\white-customizable-icon.png (updated file)
  copy  www\img\white-next-arrow-icon.png platforms\android\app\src\main\assets\www\img\white-next-arrow-icon.png (updated file)
  copy  www\index.html platforms\android\app\src\main\assets\www\index.html (updated file)
  copy  www\js\index.js platforms\android\app\src\main\assets\www\js\index.js (updated file)
  copy  www\js\login.js platforms\android\app\src\main\assets\www\js\login.js (updated file)
  copy  www\nodejs-project\main.js platforms\android\app\src\main\assets\www\nodejs-project\main.js (updated file)
  copy  platforms\android\platform_www\plugins\nodejs-mobile-cordova\www\nodejs_apis.js platforms\android\app\src\main\assets\www\plugins\nodejs-mobile-cordova\www\nodejs_apis.js (updated file)
  copy  platforms\android\platform_www\plugins\nodejs-mobile-cordova\www\nodejs_events.js platforms\android\app\src\main\assets\www\plugins\nodejs-mobile-cordova\www\nodejs_events.js (updated file)
Wrote out android application name "HelloCordova" to W:\Programming\Web Apps\Mais Entregas Para Motoristas\MaisEntregas\platforms\android\app\src\main\res\values\strings.xml
Wrote out Android application SplashScreen Color to W:\Programming\Web Apps\Mais Entregas Para Motoristas\MaisEntregas\platforms\android\app\src\main\res\values\colors.xml
The "AndroidWindowSplashScreenAnimatedIcon" is undefined. Cordova's default will be used.
The "AndroidWindowSplashScreenBrandingImage" is undefined. Cordova's default will be used.
Wrote out Android application SplashScreen Icon Color to W:\Programming\Web Apps\Mais Entregas Para Motoristas\MaisEntregas\platforms\android\app\src\main\res\values\colors.xml
Wrote out Android application themes to W:\Programming\Web Apps\Mais Entregas Para Motoristas\MaisEntregas\platforms\android\app\src\main\res\values\themes.xml
[Cordova Gradle Config] Setting "PACKAGE_NAMESPACE" to com.KledsonZG.MaisEntregas
[Cordova Gradle Config] Saving File
android-versionCode not found in config.xml. Generating a code based on version in config.xml (1.0.0): 10000
This app does not have launcher icons defined
This app does not have additional resource files defined
Prepared android project successfully
Executing script found in plugin nodejs-mobile-cordova for hook "after_prepare": plugins\nodejs-mobile-cordova\install\hooks\android\after-prepare-build-node-assets-lists.js
Executing script found in plugin nodejs-mobile-cordova for hook "after_prepare": plugins\nodejs-mobile-cordova\install\hooks\both\after-prepare-patch-npm-packages.js
The "path" argument must be of type string. Received undefined
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:387:5)
    at validateString (node:internal/validators:162:11)
    at Object.join (node:path:429:7)
    at new Api (W:\Programming\Web Apps\Mais Entregas Para Motoristas\MaisEntregas\node_modules\cordova-android\lib\Api.js:65:30)
    at patchTargetPlatform (W:\Programming\Web Apps\Mais Entregas Para Motoristas\MaisEntregas\plugins\nodejs-mobile-cordova\install\hooks\both\after-prepare-patch-npm-packages.js:57:29)
    at module.exports (W:\Programming\Web Apps\Mais Entregas Para Motoristas\MaisEntregas\plugins\nodejs-mobile-cordova\install\hooks\both\after-prepare-patch-npm-packages.js:68:5)
    at runScriptViaModuleLoader (C:\Users\kleds\AppData\Roaming\nvm\v16.20.2\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:157:32)
    at runScript (C:\Users\kleds\AppData\Roaming\nvm\v16.20.2\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:136:12)
    at C:\Users\kleds\AppData\Roaming\nvm\v16.20.2\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:108:40
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:387:5)
    at validateString (node:internal/validators:162:11)
    at Object.join (node:path:429:7)
    at new Api (W:\Programming\Web Apps\Mais Entregas Para Motoristas\MaisEntregas\node_modules\cordova-android\lib\Api.js:65:30)
    at patchTargetPlatform (W:\Programming\Web Apps\Mais Entregas Para Motoristas\MaisEntregas\plugins\nodejs-mobile-cordova\install\hooks\both\after-prepare-patch-npm-packages.js:57:29)
    at module.exports (W:\Programming\Web Apps\Mais Entregas Para Motoristas\MaisEntregas\plugins\nodejs-mobile-cordova\install\hooks\both\after-prepare-patch-npm-packages.js:68:5)
    at runScriptViaModuleLoader (C:\Users\kleds\AppData\Roaming\nvm\v16.20.2\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:157:32)
    at runScript (C:\Users\kleds\AppData\Roaming\nvm\v16.20.2\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:136:12)
    at C:\Users\kleds\AppData\Roaming\nvm\v16.20.2\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:108:40
```

**Comment by derekdavenport** [comment]
Yeah I got this on a fresh project with only the demo code. Looks like the Cordova API requires some parameters that this plugin doesn't supply. So probably need an older version of Cordova.

**Comment by olamarvel** [comment]
What version would I have to downgrade to? and is there any resource on doing this?

**Comment by derekdavenport** [comment]
I gave up at this point, at least on using Cordova. But since this project hasn't been updated in 3 years, I'd guess a version from about 3 years ago.

**Comment by olamarvel** [comment]
> I gave up at this point, at least on using Cordova. But since this project hasn't been updated in 3 years, I'd guess a version from about 3 years ago.

I gave up also 😅
