### ISSUE TITLE
Error running nodejs library

### ISSUE THREAD

**Issue by RyszardRzepa** [janeasystems/nodejs-mobile#54]
Hey,

I was trying to run package 'opencv4nodejs' in react native app  using `nodejs-mobile-react-native`.

`nodejs-mobile-react-native ` works very well and I manage to run IOS app with node 'express' package. Next After succesfull installed opencv4nodejs,
and inporting `var cv = require('opencv4nodejs')`, I am getting an error:

```
Error: dlopen(/Users/ryrz01/Library/Developer/CoreSimulator/Devices/55B8702F-DC21-4EC4-8440-3A420CA895E8/data/Containers/Bundle/Application/018299DA-823D-4B36-A001-B48193BD0235/nodeJs_demo.app/nodejs-project/node_modules/opencv4nodejs/build/Release/opencv4nodejs.node, 1): no suitable image found.  Did find:
	/Users/ryrz01/Library/Developer/CoreSimulator/Devices/55B8702F-DC21-4EC4-8440-3A420CA895E8/data/Containers/Bundle/Application/018299DA-823D-4B36-A001-B48193BD0235/nodeJs_demo.app/nodejs-project/node_modules/opencv4nodejs/build/Release/opencv4nodejs.node: mach-o, but not built for iOS simulator
   at Module._extensions[.node] (module.js:653:3)
   at Module.prototype.load (module.js:545:3)
   at tryModuleLoad (module.js:508:5)
   at Module._load (module.js:500:3)
   at Module.prototype.require (module.js:568:3)
   at require (internal/module.js:11:7)
   at Anonymous function (/Users/ryrz01/Library/Developer/CoreSimulator/Devices/55B8702F-DC21-4EC4-8440-3A420CA895E8/data/Containers/Bundle/Application/018299DA-823D-4B36-A001-B48193BD0235/nodeJs_demo.app/nodejs-project/node_modules/opencv4nodejs/lib/opencv4nodejs.js:16:3)
   at Module.prototype._compile (module.js:624:5)
   at Module._extensions[.js] (module.js:635:3)
   at Module.prototype.load (module.js:545:3)
```

I am wondering why other node.js package works but not opencv4nodejs?

Link to the library I am trying to run: https://github.com/justadudewhohacks/opencv4nodejs

Version: output of `node -v`v9.4.0
Platform: IOS 11

**Comment by jaimecbernardo** [comment]
Hi @RyszardRzepa ,

The reason `express` runs and `opencv4nodejs` doesn't is that `opencv4nodejs` is a native module, which means it contains C++ code that needs to be compiled for the target OS/architecture.

There is a experimental way released to build native modules for iOS. You can find more about how to turn it on in the issue tracking native modules: https://github.com/janeasystems/nodejs-mobile/issues/4#issuecomment-371555631

Please let us know if you have success with `opencv4nodejs` and/or if you had to change the module for it to compile for iOS.

**Comment by RyszardRzepa** [comment]
Thanks for replay. I will let you know if I manage to use opencv4nodejs with nodejs-mobile package.

**Comment by jaimecbernardo** [comment]
Hi @RyszardRzepa ,
We've just released the v0.2.0 update for the [React Native plugin](https://github.com/janeasystems/nodejs-mobile-react-native#native-modules)

It comes with native modules improvements. Did you manage to get it working?

**Comment by RyszardRzepa** [comment]
Hi!

I didn´t mange to run `opencv4nodejs` last time. I had some weird errors. 

I will try `v0.2.0`.

**Comment by RyszardRzepa** [comment]
hei @jaimecbernardo, I did try to run  `opencv4nodejs` again on react native ios but without success.

My steps was:
1) install `nodejs-mobile-react-native` in new react native project
2) link `nodejs-mobile-react-native`
3) run on ios simulator - everything works.
4) install `opencv4nodejs` in `nodejs-project/` folder
5) add file `BUILD_NATIVE_MODULES.txt` in `nodejs-project/` folder with content `NODEJS_MOBILE_BUILD_NATIVE_MODULES=1`
6) require `var cv = require('opencv4nodejs')` in `main.js` file for testing.
7) run ios simulator.

The build for ios simulator still a success, but it opens the app and crashes straight away.  

Did I miss any step to run native module on IOS ? 

Error message:
 `Error: dlopen(/Users/ryrz01/Library/Developer/CoreSimulator/Devices/16D06F98-2473-4F8B-AC97-E6EE835D9CC4/data/Containers/Bundle/Application/E7C22164-A5CC-4053-8A6B-1CAF6F474B44/nodeJs_react_native.app/Frameworks/nodecbe9f4f4fba7150e97a931b101b6fb2bf15f237a.framework/nodecbe9f4f4fba7150e97a931b101b6fb2bf15f237a, 1): Library not loaded: @rpath/libopencv_core.3.4.dylib
  Referenced from: /Users/ryrz01/Library/Developer/CoreSimulator/Devices/16D06F98-2473-4F8B-AC97-E6EE835D9CC4/data/Containers/Bundle/Application/E7C22164-A5CC-4053-8A6B-1CAF6F474B44/nodeJs_react_native.app/Frameworks/nodecbe9f4f4fba7150e97a931b101b6fb2bf15f237a.framework/nodecbe9f4f4fba7150e97a931b101b6fb2bf15f237a
  Reason: no suitable image found.  Did find:
	/Users/ryrz01/Library/Developer/Xcode/DerivedData/nodeJs_react_native-ckeyncyyxdooxrezigeqibraqqog/Build/Products/Debug-iphonesimulator/nodeJs_react_native.app/nodejs-project/node_modules/opencv-build/opencv/build/lib/libopencv_core.3.4.dylib: mach-o, but not built for iOS simulator
   at process.dlopen (/Users/ryrz01/Library/Developer/CoreSimulator/Devices/16D06F98-2473-4F8B-AC97-E6EE835D9CC4/data/Containers/Bundle/Application/E7C22164-A5CC-4053-8A6B-1CAF6F474B44/nodeJs_react_native.app/nodejs-project/override-dlopen-paths-preload.js:23:5)
   at Module._extensions[.node] (module.js:653:3)
   at Module.prototype.load (module.js:545:3)
   at tryModuleLoad (module.js:508:5)
   at Module._load (module.js:500:3)
   at Module.prototype.require (module.js:568:3)
   at require (internal/module.js:11:7)
   at Anonymous function (/Users/ryrz01/Library/Developer/CoreSimulator/Devices/16D06F98-2473-4F8B-AC97-E6EE835D9CC4/data/Containers/Bundle/Application/E7C22164-A5CC-4053-8A6B-1CAF6F474B44/nodeJs_react_native.app/nodejs-project/node_modules/opencv4nodejs/lib/cv.js:17:3)
   at Module.prototype._compile (module.js:624:5)
   at Module._extensions[.js] (module.js:635:3)
`

**Comment by jaimecbernardo** [comment]
Hi @RyszardRzepa ,
Your steps are fine, but step 5 should be:
- add file `BUILD_NATIVE_MODULES.txt` in `nodejs-assets/` folder with content `1` : `echo "1" > nodejs-assets/BUILD_NATIVE_MODULES.txt`

This step shouldn't matter in the latest version of the plugin, though, as it detects native modules automatically.

I gave it a try and was unable to run it as well. The error you're getting is that `opencv4nodejs` is trying to load a `dylib` shared library, so this means it has some custom logic for other build steps. These seem to come from the `opencv-build` dependency: https://github.com/justadudewhohacks/opencv4nodejs/blob/2d6189adc5ec00ee669269626abb42a58dd13750/binding.gyp#L153

`opencv-build` would most likeky have to be investigated and changed for it to build for iOS as well: https://github.com/justadudewhohacks/npm-opencv-build/blob/master/install.js

**Comment by RyszardRzepa** [comment]
Thanks @jaimecbernardo  for giving a try. 

The creator of `opencv4nodejs`  library pointet out: 

> You can only use node modules with react native, which are not or do not use native node modules. Opencv4nodejs is a native nodejs module, which has to be compiled for a specific OS, architecture, node ABI etc.

> Furthermore it requires an OpenCV setup, which has to be also compiled for a specific platform. You can build OpenCV for android or IOS if desired, but you would have to consume it in the native language (java / objective C).

https://github.com/justadudewhohacks/opencv4nodejs/issues/214#issuecomment-375194056

I am really interested if I could run `node js `binding to `opencv` with `nodejs-mobile`.
Running ML models and custom server locally within react-native app sounds amazing! :D
