### ISSUE TITLE
 couldn't find "libnodejs-mobile-cordova-native-lib.so"

### ISSUE THREAD

**Issue by MaxymSemenykhin** [janeasystems/nodejs-mobile#56]
Hi!
I am trying to use this plugin but i am getting errors from logcat

```
03-26 11:18:47.149   559   889 I zygote64: Rejecting re-init on previously-failed class java.lang.Class<com.janeasystems.cdvnodejsmobile.NodeJS>: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.myproject-FoPsAGRQCNpM6JXLdxWNCQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.myproject-FoPsAGRQCNpM6JXLdxWNCQ==/lib/arm64, /system/lib64, /vendor/lib64]]] couldn't find "libnodejs-mobile-cordova-native-lib.so"
03-26 11:18:47.150   559   889 W System.err: java.lang.NoClassDefFoundError: com.janeasystems.cdvnodejsmobile.NodeJS
03-26 11:18:47.152   559   889 W System.err: Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.myproject-FoPsAGRQCNpM6JXLdxWNCQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.myproject-FoPsAGRQCNpM6JXLdxWNCQ==/lib/arm64, /system/lib64, /vendor/lib64]]] couldn't find "libnodejs-mobile-cordova-native-lib.so"
03-26 11:18:47.153   559   889 W System.err:    at com.janeasystems.cdvnodejsmobile.NodeJS.<clinit>(NodeJS.java:62)
03-26 11:18:50.973   559   889 I zygote64: Rejecting re-init on previously-failed class java.lang.Class<com.janeasystems.cdvnodejsmobile.NodeJS>: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.myproject-FoPsAGRQCNpM6JXLdxWNCQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.myproject-FoPsAGRQCNpM6JXLdxWNCQ==/lib/arm64, /system/lib64, /vendor/lib64]]] couldn't find "libnodejs-mobile-cordova-native-lib.so"
03-26 11:18:50.975   559   889 W System.err: java.lang.NoClassDefFoundError: com.janeasystems.cdvnodejsmobile.NodeJS
03-26 11:18:50.981   559   889 W System.err: Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.myproject-FoPsAGRQCNpM6JXLdxWNCQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.myproject-FoPsAGRQCNpM6JXLdxWNCQ==/lib/arm64, /system/lib64, /vendor/lib64]]] couldn't find "libnodejs-mobile-cordova-native-lib.so"
03-26 11:18:50.982   559   889 W System.err:    at com.janeasystems.cdvnodejsmobile.NodeJS.<clinit>(NodeJS.java:62)
03-26 11:18:52.845   559   889 I zygote64: Rejecting re-init on previously-failed class java.lang.Class<com.janeasystems.cdvnodejsmobile.NodeJS>: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.myproject-FoPsAGRQCNpM6JXLdxWNCQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.myproject-FoPsAGRQCNpM6JXLdxWNCQ==/lib/arm64, /system/lib64, /vendor/lib64]]] couldn't find "libnodejs-mobile-cordova-native-lib.so"
03-26 11:18:52.845   559   889 W System.err: java.lang.NoClassDefFoundError: com.janeasystems.cdvnodejsmobile.NodeJS
03-26 11:18:52.847   559   889 W System.err: Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.myproject-FoPsAGRQCNpM6JXLdxWNCQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.myproject-FoPsAGRQCNpM6JXLdxWNCQ==/lib/arm64, /system/lib64, /vendor/lib64]]] couldn't find "libnodejs-mobile-cordova-native-lib.so"
03-26 11:18:52.847   559   889 W System.err:    at com.janeasystems.cdvnodejsmobile.NodeJS.<clinit>(NodeJS.java:62)
```

Can anyone help with this issue?

**Comment by jaimecbernardo** [comment]
Hi @MaxymSemenykhin, it seems the error is  related to your Android Application trying to find the 64 bit version of the node library. What versions of Cordova and `Cordova-android` are you using?

**Comment by MaxymSemenykhin** [comment]
@jaimecbernardo 
$ cordova -v
7.0.0

**Comment by jaimecbernardo** [comment]
Hi @MaxymSemenykhin,

There shouldn't be such problems in cordova 7.0.0 , since it should use the 32 bits version of the plugin on Android. (Assuming the version of `cordova-android` is still the same that comes with `cordova 7.0.0`, and that's why I asked)

I couldn't replicate your problem with the provided information.

**Comment by jaimecbernardo** [comment]
Has anyone else that faced the same problem and solved it?

**Comment by MaxymSemenykhin** [comment]
@jaimecbernardo 

> Assuming the version of cordova-android is still the same that comes with cordova 7.0.0, and that's > > why I asked

I am actually not sure how to check `cordova-android` version

**Comment by MaxymSemenykhin** [comment]
@jaimecbernardo ok, let's start from other side.
Do you know where this `libnodejs-mobile-cordova-native-lib.so` should came from? is it provided by cordova, by android or should be imported from this plugin?

**Comment by jaimecbernardo** [comment]
@MaxymSemenykhin You can see the installed platforms in a Cordova project by running `cordova platform` inside.
`libnodejs-mobile-cordova-native-lib.so` is supposed to be compiled by Gradle as part of the `cordova-android` template application using the files that come from the `nodejs-mobile-cordova` plugin. Only 32 bit binaries were supposed to be built, though, and your application seems to be looking for a 64 bit binary.

**Comment by Rudimo** [comment]
@MaxymSemenykhin Hello. Did you manage to solve this problem?

**Comment by MaxymSemenykhin** [comment]
@Rudimo actually i did not :( I gave up on this plugin

**Comment by jaimecbernardo** [comment]
@Rudimo ,
Could you please run `cordova -v` and `cordova platform` in the project to get the versions being used?
The version of the android platform that comes with the supported `cordova 7.X` shouldn't have this error.

@MaxymSemenykhin , that's too bad. Couldn't understand what's going on without getting more information that allows me to reproduce it.

**Comment by Rudimo** [comment]
@jaimecbernardo ,
The problem occurs on the device with Android 5.0 API 21. On other devices with a larger version, everything is fine.

This is an ionic application. I use nodejs-mobile-cordova plugin v.0.1.4
cordova -v **8.0.0**
cordova-android: **"6.4.0"**
If i use cordova-android 7.0.0 or 7.1.0, the ionic application is not built at all. All the plug-ins are not installed.

**Comment by Rudimo** [comment]
@jaimecbernardo Oh, sorry
_Cordova 7.x (Cordova 8.x is currently not supported)_
Is this about the global cordova version?

**Comment by jaimecbernardo** [comment]
@Rudimo ,
Thank you for the additional information.

The issue with `cordova 8.x` not being supported is that it comes with `cordova-android 7.x`, which is what is not supported, since it changes the Android project structure.

The issues you're having are occurring on Android API 21. Perhaps the dynamic library load is implemented differently on that API level.
Would you mind posting the error messages here, to see if they are the same and if they give some sort of clue? Unfortunately, the lowest API device I have available is Android 5.1 API 22, so I'm unable to test in the same conditions.

Also, what specific device is it?
