### ISSUE TITLE
Building leveldown as a native module fails

### ISSUE THREAD

**Issue by clooudch** [janeasystems/nodejs-mobile#64]
Hello

I am trying to get leveldown to run on iOS with nodejs-mobile. I've added leveldown as a dependency to my nodejs-project and I also created the file BUILD_NATIVE_MODULES.txt (with content 1) to enable native module building. Now when i try to build my simple demo application from xcode, the build-script "Build NodeJS Mobile Native Modules" gets executed, detects leveldown as a native module and tries to build it. Sadly it fails and outputs the following log:

```npm info lifecycle leveldown@3.0.0~install: leveldown@3.0.0

> leveldown@3.0.0 install /Users/cfrei/Library/Developer/Xcode/DerivedData/musiclib-fndafflswbxospcrvoxzfwrblxwh/Build/Products/Debug-iphonesimulator/musiclib.app/nodejs-project/node_modules/musiclib-api/node_modules/leveldown
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 2.5.1
prebuild-install info install installing standalone, skipping download.
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '/Users/cfrei/Documents/Projects/musiclib/package/musiclib-app-mobile/node_modules/nodejs-mobile-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@0.1.1
gyp info using node@8.3.0 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/local/bin/python2
gyp verb check python version `/usr/local/bin/python2 -c "import platform; print(platform.python_version());"` returned: "2.7.14\n"
gyp verb get node dir compiling against specified --nodedir dev files: /Users/cfrei/Documents/Projects/musiclib/package/musiclib-app-mobile/node_modules/nodejs-mobile-react-native/ios/libnode
gyp verb build dir attempting to create "build" dir: /Users/cfrei/Library/Developer/Xcode/DerivedData/musiclib-fndafflswbxospcrvoxzfwrblxwh/Build/Products/Debug-iphonesimulator/musiclib.app/nodejs-project/node_modules/musiclib-api/node_modules/leveldown/build
gyp verb build dir "build" dir needed to be created? /Users/cfrei/Library/Developer/Xcode/DerivedData/musiclib-fndafflswbxospcrvoxzfwrblxwh/Build/Products/Debug-iphonesimulator/musiclib.app/nodejs-project/node_modules/musiclib-api/node_modules/leveldown/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /Users/cfrei/Library/Developer/Xcode/DerivedData/musiclib-fndafflswbxospcrvoxzfwrblxwh/Build/Products/Debug-iphonesimulator/musiclib.app/nodejs-project/node_modules/musiclib-api/node_modules/leveldown/build/config.gypi
gyp verb config.gypi checking for gypi file: /Users/cfrei/Library/Developer/Xcode/DerivedData/musiclib-fndafflswbxospcrvoxzfwrblxwh/Build/Products/Debug-iphonesimulator/musiclib.app/nodejs-project/node_modules/musiclib-api/node_modules/leveldown/config.gypi
gyp verb common.gypi checking for gypi file: /Users/cfrei/Library/Developer/Xcode/DerivedData/musiclib-fndafflswbxospcrvoxzfwrblxwh/Build/Products/Debug-iphonesimulator/musiclib.app/nodejs-project/node_modules/musiclib-api/node_modules/leveldown/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/local/bin/python2
gyp info spawn args [ '/Users/cfrei/Documents/Projects/musiclib/package/musiclib-app-mobile/node_modules/nodejs-mobile-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/cfrei/Library/Developer/Xcode/DerivedData/musiclib-fndafflswbxospcrvoxzfwrblxwh/Build/Products/Debug-iphonesimulator/musiclib.app/nodejs-project/node_modules/musiclib-api/node_modules/leveldown/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/cfrei/Documents/Projects/musiclib/package/musiclib-app-mobile/node_modules/nodejs-mobile-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/cfrei/Documents/Projects/musiclib/package/musiclib-app-mobile/node_modules/nodejs-mobile-react-native/ios/libnode/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/cfrei/Documents/Projects/musiclib/package/musiclib-app-mobile/node_modules/nodejs-mobile-react-native/ios/libnode',
gyp info spawn args   '-Dnode_gyp_dir=/Users/cfrei/Documents/Projects/musiclib/package/musiclib-app-mobile/node_modules/nodejs-mobile-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/cfrei/Documents/Projects/musiclib/package/musiclib-app-mobile/node_modules/nodejs-mobile-react-native/ios/libnode/$(Configuration)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/cfrei/Library/Developer/Xcode/DerivedData/musiclib-fndafflswbxospcrvoxzfwrblxwh/Build/Products/Debug-iphonesimulator/musiclib.app/nodejs-project/node_modules/musiclib-api/node_modules/leveldown',
gyp info spawn args   '-Dnode_engine=chakracore',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: Undefined variable os_include in /Users/cfrei/Library/Developer/Xcode/DerivedData/musiclib-fndafflswbxospcrvoxzfwrblxwh/Build/Products/Debug-iphonesimulator/musiclib.app/nodejs-project/node_modules/musiclib-api/node_modules/leveldown/deps/snappy/snappy.gyp while loading dependencies of /Users/cfrei/Library/Developer/Xcode/DerivedData/musiclib-fndafflswbxospcrvoxzfwrblxwh/Build/Products/Debug-iphonesimulator/musiclib.app/nodejs-project/node_modules/musiclib-api/node_modules/leveldown/deps/leveldb/leveldb.gyp while loading dependencies of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/cfrei/Documents/Projects/musiclib/package/musiclib-app-mobile/node_modules/nodejs-mobile-gyp/lib/configure.js:341:16)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 17.4.0
gyp ERR! command "/usr/local/bin/node" "/Users/cfrei/Documents/Projects/musiclib/package/musiclib-app-mobile/node_modules/nodejs-mobile-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/cfrei/Library/Developer/Xcode/DerivedData/musiclib-fndafflswbxospcrvoxzfwrblxwh/Build/Products/Debug-iphonesimulator/musiclib.app/nodejs-project/node_modules/musiclib-api/node_modules/leveldown
gyp ERR! node -v v8.3.0
gyp ERR! node-gyp -v v0.1.1
gyp ERR! not ok 
npm verb lifecycle leveldown@3.0.0~install: unsafe-perm in lifecycle true
npm verb lifecycle leveldown@3.0.0~install: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/cfrei/Library/Developer/Xcode/DerivedData/musiclib-fndafflswbxospcrvoxzfwrblxwh/Build/Products/Debug-iphonesimulator/musiclib.app/nodejs-project/node_modules/musiclib-api/node_modules/leveldown/node_modules/.bin:/Users/cfrei/Library/Developer/Xcode/DerivedData/musiclib-fndafflswbxospcrvoxzfwrblxwh/Build/Products/Debug-iphonesimulator/musiclib.app/nodejs-project/node_modules/musiclib-api/node_modules/.bin:/Users/cfrei/Library/Developer/Xcode/DerivedData/musiclib-fndafflswbxospcrvoxzfwrblxwh/Build/Products/Debug-iphonesimulator/musiclib.app/nodejs-project/node_modules/.bin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/local/bin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/libexec:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/local/bin:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/usr/bin:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/usr/local/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/local/bin:/Applications/Xcode.app/Contents/Developer/Tools:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
npm verb lifecycle leveldown@3.0.0~install: CWD: /Users/cfrei/Library/Developer/Xcode/DerivedData/musiclib-fndafflswbxospcrvoxzfwrblxwh/Build/Products/Debug-iphonesimulator/musiclib.app/nodejs-project/node_modules/musiclib-api/node_modules/leveldown
npm info lifecycle leveldown@3.0.0~install: Failed to exec install script
npm verb stack Error: leveldown@3.0.0 install: `prebuild-install || node-gyp rebuild`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
npm verb stack     at emitTwo (events.js:125:13)
npm verb stack     at EventEmitter.emit (events.js:213:7)
npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at emitTwo (events.js:125:13)
npm verb stack     at ChildProcess.emit (events.js:213:7)
npm verb stack     at maybeClose (internal/child_process.js:927:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
npm verb pkgid leveldown@3.0.0
npm verb cwd /Users/cfrei/Library/Developer/Xcode/DerivedData/musiclib-fndafflswbxospcrvoxzfwrblxwh/Build/Products/Debug-iphonesimulator/musiclib.app/nodejs-project
npm verb Darwin 17.4.0
npm verb argv "/usr/local/bin/node" "/usr/local/bin/npm" "--verbose" "rebuild" "--build-from-source"
npm verb node v8.3.0
npm verb npm  v5.6.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leveldown@3.0.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the leveldown@3.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]
```

I have no idea how it works and why it fails. It seems like it fails at configuring node-gyp and running the install-script. When running node-gyp in the directory of leveldown then it works as expected and build leveldown.node for macOS (darwin).

Can someone help my or point me in the right direction? I have absolutely no experience in build native modules.

Thank you for your time.

**Comment by jaimecbernardo** [comment]
Hi @clooudch ,
I've gathered some notes from a previous attempt at building leveldown for iOS. I'm sharing those here. I hope this helps and please let us know if it works nicely at runtime for your case. After this is battle tested we plan on opening a PR to leveldown.

## iOS
For building leveldown for iOS, you need to add settings similar to the ones you have on macOS.

1 - Add a line for iOS after the mac line in `deps/snappy/snappy.gyp`  https://github.com/Level/leveldown/blob/8b03831f1d826c326c14555e471f45bffd817fe9/deps/snappy/snappy.gyp#L6 :
```py
  , ['OS=="android"', {'os_include': 'linux'}]
  , ['OS=="mac"',     {'os_include': 'mac'}]
  , ['OS=="ios"',     {'os_include': 'mac'}] # Add this line to use mac includes for ios
  , ['OS=="solaris"', {'os_include': 'solaris'}]
```

2 - Add a section in `deps/leveldb/leveldb.gyp`  https://github.com/Level/leveldown/blob/8b03831f1d826c326c14555e471f45bffd817fe9/deps/leveldb/leveldb.gyp#L131-L144 similar to the one for macOS:

```py
      , ['OS == "ios"', {
            'defines': [
                'OS_IOS=1'
            ]
          , 'libraries': []
          , 'ccflags': []
          , 'xcode_settings': {
                'WARNING_CFLAGS': [
                    '-Wno-sign-compare'
                  , '-Wno-unused-variable'
                  , '-Wno-unused-function'
                ]
            }
        }]
```

3 - Add a ` || defined(OS_IOS)` next to every `defined(OS_MACOSX)` check in deps/leveldb/leveldb-1.20/port/port_posix.h https://github.com/Level/leveldown/blob/8b03831f1d826c326c14555e471f45bffd817fe9/deps/leveldb/leveldb-1.20/port/port_posix.h
  - [This line](https://github.com/Level/leveldown/blob/8b03831f1d826c326c14555e471f45bffd817fe9/deps/leveldb/leveldb-1.20/port/port_posix.h#L11) should be `#if defined(OS_MACOSX) || defined(OS_IOS)`
  - [This line](https://github.com/Level/leveldown/blob/8b03831f1d826c326c14555e471f45bffd817fe9/deps/leveldb/leveldb-1.20/port/port_posix.h#L53) should be `#if defined(OS_MACOSX) || defined(OS_IOS) || defined(OS_SOLARIS) || defined(OS_FREEBSD) ||\`
  - [This line](https://github.com/Level/leveldown/blob/8b03831f1d826c326c14555e471f45bffd817fe9/deps/leveldb/leveldb-1.20/port/port_posix.h#L62) should be `#if defined(OS_MACOSX) || defined(OS_IOS) || defined(OS_FREEBSD) ||\`

**Comment by clooudch** [comment]
Thank you very much for your  fast and very helpful comment.

I tried it out and it worked very well (at least for my simple prototype). Have you already prepared a fork of leveldown for this? It would be easier if we had a fork to which we can refer to in the package.json, instead of making these changes manually.

I am closing this now, since my question has been answered.

**Comment by axxag** [comment]
Created a PR for this - https://github.com/Level/leveldown/pull/447

**Comment by ralphtheninja** [comment]
https://github.com/Level/leveldown/releases/tag/v3.0.2
