### ISSUE TITLE
Unable to run within react native

### ISSUE THREAD

**Issue by rsingh-27** [janeasystems/nodejs-mobile#68]
* **Version**: v7.7.4
* **Platform**: MacBook-Air.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
* **Subsystem**: react-native-cli: 2.0.1 react-native: 0.55.3

Hi, I am trying to make this work on React native.
The project gest built but I get this error 

```
 bundling failed: SyntaxError: Unexpected token } in JSON at position 384
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (/Users/romeo/Desktop/React Native  Projects/RiplPay/node_modules/jest-haste-map/build/worker.js:25:29)
    at Generator.next (<anonymous>)
    at step (/Users/romeo/Desktop/React Native  Projects/RiplPay/node_modules/jest-haste-map/build/worker.js:100:191)
    at /Users/romeo/Desktop/React Native  Projects/RiplPay/node_modules/jest-haste-map/build/worker.js:100:437
    at Object.<anonymous> (/Users/romeo/Desktop/React Native  Projects/RiplPay/node_modules/jest-haste-map/build/worker.js:100:99)
    at Object.worker (/Users/romeo/Desktop/React Native  Projects/RiplPay/node_modules/jest-haste-map/build/worker.js:56:17)
    at execMethod (/Users/romeo/Desktop/React Native  Projects/RiplPay/node_modules/jest-worker/build/child.js:92:29)
    at process.on (/Users/romeo/Desktop/React Native  Projects/RiplPay/node_modules/jest-worker/build/child.js:42:7)
    at emitTwo (events.js:106:13)
 BUNDLE  [ios, dev] ./index.js ░░░░░░░░░░░░░░░░ 0.0% (0/1), failed.

```
Can you please help 
PS: I am running in iOS simulator

**Comment by rsingh-27** [comment]
This comes sometimes, doing the installation again fixes this
