### ISSUE TITLE
Node assets copy failed  

### ISSUE THREAD

**Issue by sOm2y** [janeasystems/nodejs-mobile#69]
Hi team, I've got nodejs react naitve mobile up and runing with very basic nodejs index.js.
However, when I was trying copy entire project to nodejs-project folder and successfully installed all node=modules. When I run the app I keep getting node assets copy failed, apparently the file is there, it seems like a very random error. Any thoughts on that? Tested on android 7.1.1 and 8.0

I figured out is android studio ignored all file/folders starts with underscore since underscore means private
Still need a clever solution here instead using bash script to renaming every file/folder start with underscore. 

```05-08 21:57:05.760 5361-5388/com.nimiqpocketandroid E/AndroidRuntime: FATAL EXCEPTION: Thread-3
    Process: com.nimiqpocketandroid, PID: 5361
    java.lang.RuntimeException: Node assets copy failed
        at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobileModule$1.run(RNNodeJsMobileModule.java:86)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: java.io.FileNotFoundException: nodejs-project/node_modules/jasmine-core/images/__pycache__/__init__.cpython-36.pyc
        at android.content.res.AssetManager.openAsset(Native Method)
        at android.content.res.AssetManager.open(AssetManager.java:347)
        at android.content.res.AssetManager.open(AssetManager.java:321)
        at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobileModule.copyAsset(RNNodeJsMobileModule.java:370)
        at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobileModule.copyNodeJsAssets(RNNodeJsMobileModule.java:312)
        at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobileModule.access$100(RNNodeJsMobileModule.java:25)
        at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobileModule$1.run(RNNodeJsMobileModule.java:83)
        at java.lang.Thread.run(Thread.java:761)

**Comment by jaimecbernardo** [comment]
Hi @sOm2y ,

I think it's the underscore as well.

I suggest the following workaround to override the android packager default behavior: https://github.com/janeasystems/nodejs-mobile/issues/60#issuecomment-378088756

**Comment by luandro** [comment]
Hey @jaimecbernardo, I'm also getting this in another test project I've started. I've got the underscore fix in place but still get this error crashing the application.

```
    java.lang.RuntimeException: Node assets copy failed
        at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobileModule$1.run(RNNodeJsMobileModule.java:86)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.io.FileNotFoundException: nodejs-native-assets-armeabi-v7a/node_modules/fsevents/build/Release/.node
        at android.content.res.AssetManager.openAsset(Native Method)
        at android.content.res.AssetManager.open(AssetManager.java:313)
        at android.content.res.AssetManager.open(AssetManager.java:287)
        at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobileModule.copyAsset(RNNodeJsMobileModule.java:370)
        at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobileModule.copyNativeAssetsFrom(RNNodeJsMobileModule.java:279)
        at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobileModule.copyNodeJsAssets(RNNodeJsMobileModule.java:319)
        at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobileModule.access$100(RNNodeJsMobileModule.java:25)
        at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobileModule$1.run(RNNodeJsMobileModule.java:83)
        at java.lang.Thread.run(Thread.java:818) 
```

**Comment by sOm2y** [comment]
@jaimecbernardo thanks for the answer, yes it is the underscore. once I get rid of all underscore, project is running without errors.

**Comment by jaimecbernardo** [comment]
In @luandro case, it's caused by a file starting with dot (`.`).

The default pattern is this:
`"!.svn:!.git:!.ds_store:!*.scc:.*:<dir>_*:!CVS:!thumbs.db:!picasa.ini:!*~"`
But after removing the dirs starting with underscore pattern (`<dir>_*`), there's still this small pattern: `.*`
The ignore assets pattern needed in that case is this one (removing both unwanted patterns):
`ignoreAssetsPattern '!.svn:!.git:!.ds_store:!*.scc:!CVS:!thumbs.db:!picasa.ini:!*~'`

I'll add a comment to https://github.com/janeasystems/nodejs-mobile/issues/60 that the pattern should be edited depending on the file that is causing issues.

**Comment by calm-rad** [comment]
@jaimecbernardo After making the change in your latest comment, I still have the exact same error that @luandro had. Are there other possible causes for the issue that I could check for?

**Comment by jaimecbernardo** [comment]
Hi @calm-rad , Is it on the same file?

**Comment by DankoHR** [comment]
Hi @jaimecbernardo, I have the exact same error as @luandro and @calm-rad. I have adjusted the pattern in the two build.gradle files as described but no avail.
I also had an error with the folders starting with underscore before, but after setting the above pattern the underscore error disappeared and now I have the error with the .node file within fsevents node module. Removing the ":.*" part in the pattern did not help.

Any idea how to fix this?

**Comment by heiner-max-app** [comment]
Hi @jaimecbernardo, exactly the same (like DankoHR) here in Switzerland: '.node' file causes android crash and removing .* does not help.
java.io.FileNotFoundException: nodejs-native-assets-armeabi-v7a/node_modules/fsevents/build/Release/.node
Thankful for any help here.

**Comment by jaimecbernardo** [comment]
Hi @DankoHR and @heiner-max-app ,
`fsevents` is supposed to be a macOS only library: https://www.npmjs.com/package/fsevents
Removing it from you project might be the right way to solve your issue.
