### ISSUE TITLE
java.lang.RuntimeException: Node assets copy failed

### ISSUE THREAD

**Issue by albertpb** [janeasystems/nodejs-mobile#78]
I'm trying to install realm in nodejs-project, it compiles fine but the app closes immediately 

`06-12 17:31:35.617 24882-24933/cl.iq_access E/AndroidRuntime: FATAL EXCEPTION: Thread-4
    Process: cl.iq_access, PID: 24882
    java.lang.RuntimeException: Node assets copy failed
        at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobileModule$1.run(RNNodeJsMobileModule.java:86)
        at java.lang.Thread.run(Thread.java:776)
     Caused by: java.io.FileNotFoundException: nodejs-project/node_modules/fbjs/lib/__mocks__/base62.js
        at android.content.res.AssetManager.openAsset(Native Method)
        at android.content.res.AssetManager.open(AssetManager.java:682)
        at android.content.res.AssetManager.open(AssetManager.java:656)
        at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobileModule.copyAsset(RNNodeJsMobileModule.java:370)
        at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobileModule.copyNodeJsAssets(RNNodeJsMobileModule.java:312)
        at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobileModule.access$100(RNNodeJsMobileModule.java:25)
        at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobileModule$1.run(RNNodeJsMobileModule.java:83)
        at java.lang.Thread.run(Thread.java:776) `

version: 0.1.4,
platform: react native 0.55.2

**Comment by jaimecbernardo** [comment]
Hi @siralb3rt ,
This looks like it's caused by an issue the Android Packager has with ignoring folders starting with underscore (`__mocks__/base62.js` is the file that's not available in the APK). Please look in this issue https://github.com/janeasystems/nodejs-mobile/issues/60#issuecomment-378088756 and let us know if it helps.

**Comment by vaagnavanesyan** [comment]
@jaimecbernardo,
It helped me too. How about add this lines into "nodejs-mobile-react-native" package?

**Comment by jaimecbernardo** [comment]
Hi @Vahagn1993 ,

That's good to hear.

The reasons why we won't include this in the package are explained in the comments to the original issue about this: https://github.com/janeasystems/nodejs-mobile/issues/60#issuecomment-378088756

Here's a summary:
- These lines need to be changed in two places: the plugin and the react-native application gradle files. Only the plugin gradle file can be changed for this.
- The patterns that are needed are not the same for every application, and accepting them all would make paths that were expected to be ignored in Android to not be ignored, so that's best left as a conscious decision by the developer.

**Comment by vaagnavanesyan** [comment]
@jaimecbernardo, thanks for fast reply. Now I got it. 
BTW, I made things right in my project via [patch-package](https://github.com/ds300/patch-package)
Maybe it will be helpful for people :)
