### ISSUE TITLE
ApkSoSource: not allowing consideration 

### ISSUE THREAD

**Issue by jeffreyflynt** [janeasystems/nodejs-mobile#92]
Version:  10.6.0
Platform:  Ubuntu 18.04

When running `react-native run-android`, I get this error when viewing catlog:

```
5063  5063 D ApkSoSource: not allowing consideration of lib/x86/libnode.so: deferring to libdir
5063  5063 D ApkSoSource: not allowing consideration of lib/x86/libnodejs-mobile-react-native-native-lib.so: deferring to libdir
```
It says it cannot find these files:
nodejs-native-assets/file.list
nodejs-native-assets/dir.list

I am using the latest plugin version.

Any ideas on what I may be doing wrong?

**Comment by jaimecbernardo** [comment]
Hi @jeffreyflynt ,

I've looked for the ApkSoSource error and I've found some pages referring to possible incompatibilities with emulators on some APIs. Are you running on an emulator? What API level are you on? Have you tried running on a device?

There are some warnings when there are no files present for native modules (there are plans to remove those warnings) but it wouldn't stop your application from running. It shouldn't be those paths you mention, though, are you sure you copied them right?

Would you mind uploading your logs to a gist ( https://gist.github.com/ ) and linking it here?

**Comment by jeffreyflynt** [comment]
Yes, here it is.  Run with: adb logcat | grep nodejs

https://gist.github.com/jeffreyflynt/7dea03ba8c89eb7a0ae9ee15f613dbe6

```
07-11 20:29:10.138  7032  7449 W System.err: java.io.FileNotFoundException: nodejs-native-assets-x86/dir.list
07-11 20:29:10.139  7032  7449 W System.err: 	at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobileModule.readFileFromAssets(RNNodeJsMobileModule.java:338)
07-11 20:29:10.139  7032  7449 W System.err: 	at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobileModule.copyNativeAssetsFrom(RNNodeJsMobileModule.java:267)
07-11 20:29:10.139  7032  7449 W System.err: 	at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobileModule.copyNodeJsAssets(RNNodeJsMobileModule.java:319)
07-11 20:29:10.139  7032  7449 W System.err: 	at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobileModule.access$100(RNNodeJsMobileModule.java:25)
07-11 20:29:10.139  7032  7449 W System.err: 	at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobileModule$1.run(RNNodeJsMobileModule.java:83)
07-11 20:29:10.139  7032  7449 W System.err: java.io.FileNotFoundException: nodejs-native-assets-x86/file.list
07-11 20:29:10.140  7032  7449 W System.err: 	at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobileModule.readFileFromAssets(RNNodeJsMobileModule.java:338)
07-11 20:29:10.140  7032  7449 W System.err: 	at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobileModule.copyNativeAssetsFrom(RNNodeJsMobileModule.java:268)
07-11 20:29:10.140  7032  7449 W System.err: 	at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobileModule.copyNodeJsAssets(RNNodeJsMobileModule.java:319)
07-11 20:29:10.140  7032  7449 W System.err: 	at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobileModule.access$100(RNNodeJsMobileModule.java:25)
07-11 20:29:10.140  7032  7449 W System.err: 	at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobileModule$1.run(RNNodeJsMobileModule.java:83)
07-11 20:29:10.140  7032  7449 V NODEJS-RN: No assets to copy from nodejs-native-assets-x86
```

Yes, I am using an emulator.  I do not have an Android device to try on, I will try on iOS though.  I have tried SDK 23 and SDK 26.

The app works fine in the emulator, but I cannot echo or console any messages from Node Initialized as in the examples.

Thanks

**Comment by jaimecbernardo** [comment]
I was thinking about getting the whole logs, but if the app is working fine, there might be no error at all. The error you're getting should not be affecting the app load. (We should demote it to a warning).

It looks like you're only getting lines with lowercase "nodejs" in them. The logs from the node Runtime will have ["NODEJS-MOBILE" as the tag](https://github.com/janeasystems/nodejs-mobile-react-native/blob/fc1e2710285f0a8b5114f6d1be60a92b51704334/android/src/main/cpp/native-lib.cpp#L73), so running grep with the `-i` flag might help, for case insensitive match.

**Comment by jeffreyflynt** [comment]
Thanks for the response.

When using the -i flag, this is what I get:
```
 4156  4203 D NODEJS-RN: Node assets copy using pre-built lists
07-12 23:08:18.905  4156  4203 W System.err: java.io.FileNotFoundException: nodejs-native-assets-x86/dir.list
07-12 23:08:18.906  4156  4203 W System.err: 	at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobileModule.readFileFromAssets(RNNodeJsMobileModule.java:338)
07-12 23:08:18.906  4156  4203 W System.err: 	at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobileModule.copyNativeAssetsFrom(RNNodeJsMobileModule.java:267)
07-12 23:08:18.906  4156  4203 W System.err: 	at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobileModule.copyNodeJsAssets(RNNodeJsMobileModule.java:319)
07-12 23:08:18.906  4156  4203 W System.err: 	at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobileModule.access$100(RNNodeJsMobileModule.java:25)
07-12 23:08:18.906  4156  4203 W System.err: 	at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobileModule$1.run(RNNodeJsMobileModule.java:83)
07-12 23:08:18.906  4156  4203 W System.err: java.io.FileNotFoundException: nodejs-native-assets-x86/file.list
07-12 23:08:18.906  4156  4203 W System.err: 	at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobileModule.readFileFromAssets(RNNodeJsMobileModule.java:338)
07-12 23:08:18.906  4156  4203 W System.err: 	at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobileModule.copyNativeAssetsFrom(RNNodeJsMobileModule.java:268)
07-12 23:08:18.906  4156  4203 W System.err: 	at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobileModule.copyNodeJsAssets(RNNodeJsMobileModule.java:319)
07-12 23:08:18.906  4156  4203 W System.err: 	at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobileModule.access$100(RNNodeJsMobileModule.java:25)
07-12 23:08:18.906  4156  4203 W System.err: 	at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobileModule$1.run(RNNodeJsMobileModule.java:83)
07-12 23:08:18.906  4156  4203 V NODEJS-RN: No assets to copy from nodejs-native-assets-x86
```
I noticed in the android folder those files were under directory:
`/nodejs-native-assets-temp-build `and the Java file directory is set to: `nativeAssetsPath = BUILTIN_NATIVE_ASSETS_PREFIX + getCurrentABIName(); `I am wondering did the file not move from tmp to the correct folder?  I am not getting any console or alert messages that Node loaded.

**Comment by jeffreyflynt** [comment]
In build.gradle, `node_modules/nodejs-mobile-react-native` I changed `nodejs-native-assets-temp-build` to `nodejs-native-assets` and it works correctly now.

**Comment by jaimecbernardo** [comment]
Hi @jeffreyflynt ,

That error message should not be affecting your app. It should still start. I've tried replicating the error with an Application with no native modules ( the message shows but the app still starts ).

So, you're saying the Application only started after making the change you mentioned, which is a bit puzzling. There might be a different issue causing this.
Do you have any repo with a project to replicate this issue that you could share?

Thank you.
